// ─────────────────────────────────────────────────────────────
// HSS UK Membership Management System — Attendance Mock Data
// ─────────────────────────────────────────────────────────────

export type SessionFrequency = 'weekly' | 'fortnightly' | 'monthly' | 'one-off';
export type SessionStatus    = 'scheduled' | 'completed' | 'cancelled';
export type AttendanceStatus = 'present' | 'absent' | 'unmarked';

export const SHAKHA_TYPES = [
  'Swayamsevak Shakha',
  'Sewa Shakha',
  'Parivaar Shakha',
  'Milan',
  'Sampark Kendra',
] as const;

export type ShakhaType = typeof SHAKHA_TYPES[number];

export interface ShakhaSession {
  id: string;
  title: string;
  activityCentre: string;
  region: string;
  town: string;
  shakhaType?: ShakhaType;
  frequency: SessionFrequency;
  dayOfWeek: number;        // 0=Sun … 6=Sat
  startTime: string;        // "HH:MM"
  endTime: string;          // "HH:MM"
  date: string;             // ISO date "YYYY-MM-DD" — the specific occurrence
  status: SessionStatus;
  attendanceRecords: AttendanceRecord[];
  totalExpected: number;
}

export interface AttendanceRecord {
  memberId: string;
  memberName: string;
  gender: 'male' | 'female';
  ageCategory: 'bal' | 'shishu' | 'kishor' | 'tarun' | 'yuva' | 'jyestha';
  jobTitle: string;
  status: AttendanceStatus;
  markedAt?: string;        // ISO datetime
}

// ── Helper ────────────────────────────────────────────────────
function d(date: string) { return date; }

export function getSessionShakhaType(session: ShakhaSession): ShakhaType | '—' {
  if (session.shakhaType) return session.shakhaType;

  const titleParts = session.title.split(' — ');
  const titleSuffix = titleParts.length > 1 ? titleParts[titleParts.length - 1] : '';
  if ((SHAKHA_TYPES as readonly string[]).includes(titleSuffix)) return titleSuffix as ShakhaType;

  if (session.activityCentre.includes('Wembley')) return 'Swayamsevak Shakha';
  if (session.activityCentre.includes('Harrow')) return 'Parivaar Shakha';
  if (session.activityCentre.includes('Birmingham')) return 'Parivaar Shakha';
  if (session.activityCentre.includes('Manchester')) return 'Sewa Shakha';
  if (session.activityCentre.includes('Leeds')) return 'Milan';
  if (session.activityCentre.includes('Edinburgh')) return 'Sampark Kendra';

  return '—';
}

// ── Mock Sessions (May–June 2026, spread across centres) ─────

export const mockSessions: ShakhaSession[] = [

  // ── Wembley Activity Centre ───────────────────────────────
  {
    id: 'SES-001',
    title: 'Wembley Shakha — Weekly',
    activityCentre: 'Wembley Activity Centre',
    region: 'London & South East',
    town: 'Wembley',
    frequency: 'weekly',
    dayOfWeek: 4,
    startTime: '18:00',
    endTime:   '20:00',
    date: '2026-05-07',
    status: 'completed',
    totalExpected: 200,
    attendanceRecords: [
      // ── Present (40) ──────────────────────────────────────────────────────
      { memberId: 'MBR-001', memberName: 'Arjun Sharma',        gender: 'male',   ageCategory: 'tarun',   jobTitle: 'Karyawaha',              status: 'present', markedAt: '2026-05-07T18:05:00Z' },
      { memberId: 'MBR-006', memberName: 'Deepa Nair',          gender: 'female', ageCategory: 'tarun',   jobTitle: 'Sewa',                   status: 'present', markedAt: '2026-05-07T18:08:00Z' },
      { memberId: 'MBR-010', memberName: 'Anita Desai',         gender: 'female', ageCategory: 'tarun',   jobTitle: 'Sewa',                   status: 'present', markedAt: '2026-05-07T18:10:00Z' },
      { memberId: 'MBR-011', memberName: 'Suresh Pillai',       gender: 'male',   ageCategory: 'tarun',   jobTitle: 'Sampark',                status: 'present', markedAt: '2026-05-07T18:12:00Z' },
      { memberId: 'MBR-012', memberName: 'Meera Iyer',          gender: 'female', ageCategory: 'kishor',  jobTitle: 'Kishor(i)',              status: 'present', markedAt: '2026-05-07T18:15:00Z' },
      { memberId: 'WBL-001', memberName: 'Vikram Singh',        gender: 'male',   ageCategory: 'yuva',    jobTitle: 'Ghatnayak',              status: 'present', markedAt: '2026-05-07T18:17:00Z' },
      { memberId: 'WBL-002', memberName: 'Priya Patel',         gender: 'female', ageCategory: 'tarun',   jobTitle: 'Shikshak',               status: 'present', markedAt: '2026-05-07T18:19:00Z' },
      { memberId: 'WBL-003', memberName: 'Rahul Mehta',         gender: 'male',   ageCategory: 'tarun',   jobTitle: 'Bauddhik',               status: 'present', markedAt: '2026-05-07T18:20:00Z' },
      { memberId: 'WBL-004', memberName: 'Kavya Reddy',         gender: 'female', ageCategory: 'kishor',  jobTitle: 'Kishor(i)',              status: 'present', markedAt: '2026-05-07T18:22:00Z' },
      { memberId: 'WBL-005', memberName: 'Nikhil Joshi',        gender: 'male',   ageCategory: 'tarun',   jobTitle: 'Sampark',                status: 'present', markedAt: '2026-05-07T18:24:00Z' },
      { memberId: 'WBL-006', memberName: 'Sneha Gupta',         gender: 'female', ageCategory: 'tarun',   jobTitle: 'Sewa',                   status: 'present', markedAt: '2026-05-07T18:25:00Z' },
      { memberId: 'WBL-007', memberName: 'Amit Kumar',          gender: 'male',   ageCategory: 'yuva',    jobTitle: 'Sanghchalak',            status: 'present', markedAt: '2026-05-07T18:27:00Z' },
      { memberId: 'WBL-008', memberName: 'Nisha Kapoor',        gender: 'female', ageCategory: 'tarun',   jobTitle: 'Tarun(i)',               status: 'present', markedAt: '2026-05-07T18:28:00Z' },
      { memberId: 'WBL-009', memberName: 'Rajesh Verma',        gender: 'male',   ageCategory: 'yuva',    jobTitle: 'Mukhya Shikshak',        status: 'present', markedAt: '2026-05-07T18:30:00Z' },
      { memberId: 'WBL-010', memberName: 'Pooja Shah',          gender: 'female', ageCategory: 'tarun',   jobTitle: 'Sewa',                   status: 'present', markedAt: '2026-05-07T18:31:00Z' },
      { memberId: 'WBL-011', memberName: 'Sachin Rao',          gender: 'male',   ageCategory: 'tarun',   jobTitle: 'Shikshak',               status: 'present', markedAt: '2026-05-07T18:33:00Z' },
      { memberId: 'WBL-012', memberName: 'Lata Krishnan',       gender: 'female', ageCategory: 'yuva',    jobTitle: 'Sewa',                   status: 'present', markedAt: '2026-05-07T18:35:00Z' },
      { memberId: 'WBL-013', memberName: 'Deepak Bose',         gender: 'male',   ageCategory: 'yuva',    jobTitle: 'Karyawaha',              status: 'present', markedAt: '2026-05-07T18:36:00Z' },
      { memberId: 'WBL-014', memberName: 'Geeta Menon',         gender: 'female', ageCategory: 'jyestha', jobTitle: 'Jyestha(a)',             status: 'present', markedAt: '2026-05-07T18:38:00Z' },
      { memberId: 'WBL-015', memberName: 'Kiran Trivedi',       gender: 'male',   ageCategory: 'tarun',   jobTitle: 'Prachaar',               status: 'present', markedAt: '2026-05-07T18:40:00Z' },
      { memberId: 'WBL-016', memberName: 'Sunita Pandey',       gender: 'female', ageCategory: 'tarun',   jobTitle: 'Sewa',                   status: 'present', markedAt: '2026-05-07T18:41:00Z' },
      { memberId: 'WBL-017', memberName: 'Arun Chatterjee',     gender: 'male',   ageCategory: 'yuva',    jobTitle: 'Vyavestha',              status: 'present', markedAt: '2026-05-07T18:43:00Z' },
      { memberId: 'WBL-018', memberName: 'Maya Saxena',         gender: 'female', ageCategory: 'yuva',    jobTitle: 'Sewa',                   status: 'present', markedAt: '2026-05-07T18:45:00Z' },
      { memberId: 'WBL-019', memberName: 'Vivek Mishra',        gender: 'male',   ageCategory: 'tarun',   jobTitle: 'SSV',                    status: 'present', markedAt: '2026-05-07T18:46:00Z' },
      { memberId: 'WBL-020', memberName: 'Rekha Pillai',        gender: 'female', ageCategory: 'yuva',    jobTitle: 'Sewa',                   status: 'present', markedAt: '2026-05-07T18:48:00Z' },
      { memberId: 'WBL-021', memberName: 'Gaurav Tiwari',       gender: 'male',   ageCategory: 'tarun',   jobTitle: 'Vistaar',                status: 'present', markedAt: '2026-05-07T18:50:00Z' },
      { memberId: 'WBL-022', memberName: 'Hema Banerjee',       gender: 'female', ageCategory: 'yuva',    jobTitle: 'Hindu Sahitya Kendra',   status: 'present', markedAt: '2026-05-07T18:51:00Z' },
      { memberId: 'WBL-023', memberName: 'Yogesh Desai',        gender: 'male',   ageCategory: 'tarun',   jobTitle: 'Nidhi',                  status: 'present', markedAt: '2026-05-07T18:53:00Z' },
      { memberId: 'WBL-024', memberName: 'Kavita Agarwal',      gender: 'female', ageCategory: 'tarun',   jobTitle: 'Shakha / Activity center', status: 'present', markedAt: '2026-05-07T18:55:00Z' },
      { memberId: 'WBL-025', memberName: 'Manish Rao',          gender: 'male',   ageCategory: 'tarun',   jobTitle: 'Sankhya',                status: 'present', markedAt: '2026-05-07T18:56:00Z' },
      { memberId: 'WBL-026', memberName: 'Sonia Mehta',         gender: 'female', ageCategory: 'tarun',   jobTitle: 'Sewa',                   status: 'present', markedAt: '2026-05-07T18:58:00Z' },
      { memberId: 'WBL-027', memberName: 'Rohit Das',           gender: 'male',   ageCategory: 'kishor',  jobTitle: 'Kishor(i)',              status: 'present', markedAt: '2026-05-07T19:00:00Z' },
      { memberId: 'WBL-028', memberName: 'Aarti Dubey',         gender: 'female', ageCategory: 'kishor',  jobTitle: 'Bal(ika)',               status: 'present', markedAt: '2026-05-07T19:01:00Z' },
      { memberId: 'WBL-029', memberName: 'Pankaj Chaudhary',    gender: 'male',   ageCategory: 'tarun',   jobTitle: 'Shareerik',              status: 'present', markedAt: '2026-05-07T19:03:00Z' },
      { memberId: 'WBL-030', memberName: 'Devika Roy',          gender: 'female', ageCategory: 'tarun',   jobTitle: 'Karyalay',               status: 'present', markedAt: '2026-05-07T19:05:00Z' },
      { memberId: 'WBL-031', memberName: 'Sunil Malhotra',      gender: 'male',   ageCategory: 'yuva',    jobTitle: 'Sampark',                status: 'present', markedAt: '2026-05-07T19:06:00Z' },
      { memberId: 'WBL-032', memberName: 'Vandana Srivastava',  gender: 'female', ageCategory: 'tarun',   jobTitle: 'Tarun(i)',               status: 'present', markedAt: '2026-05-07T19:08:00Z' },
      { memberId: 'WBL-033', memberName: 'Hemant Arora',        gender: 'male',   ageCategory: 'yuva',    jobTitle: 'Mukhya Shikshak',        status: 'present', markedAt: '2026-05-07T19:10:00Z' },
      { memberId: 'WBL-034', memberName: 'Indu Ghosh',          gender: 'female', ageCategory: 'jyestha', jobTitle: 'Jyestha(a)',             status: 'present', markedAt: '2026-05-07T19:11:00Z' },
      { memberId: 'WBL-035', memberName: 'Ishaan Naik',         gender: 'male',   ageCategory: 'shishu',  jobTitle: 'Shishu',                 status: 'present', markedAt: '2026-05-07T19:13:00Z' },
      // ── Absent (160) ──────────────────────────────────────────────────────
      { memberId: 'MBR-009', memberName: 'Ravi Kumar',          gender: 'male',   ageCategory: 'tarun',   jobTitle: 'Shikshak',               status: 'absent' },
      { memberId: 'WBL-036', memberName: 'Anika Sharma',        gender: 'female', ageCategory: 'kishor',  jobTitle: 'Kishor(i)',              status: 'absent' },
      { memberId: 'WBL-037', memberName: 'Raj Patel',           gender: 'male',   ageCategory: 'tarun',   jobTitle: 'Sampark',                status: 'absent' },
      { memberId: 'WBL-038', memberName: 'Divya Singh',         gender: 'female', ageCategory: 'tarun',   jobTitle: 'Sewa',                   status: 'absent' },
      { memberId: 'WBL-039', memberName: 'Ganesh Nair',         gender: 'male',   ageCategory: 'yuva',    jobTitle: 'Ghatnayak',              status: 'absent' },
      { memberId: 'WBL-040', memberName: 'Pritha Joshi',        gender: 'female', ageCategory: 'tarun',   jobTitle: 'Shikshak',               status: 'absent' },
      { memberId: 'WBL-041', memberName: 'Rakesh Yadav',        gender: 'male',   ageCategory: 'tarun',   jobTitle: 'Bauddhik',               status: 'absent' },
      { memberId: 'WBL-042', memberName: 'Smita Gupta',         gender: 'female', ageCategory: 'yuva',    jobTitle: 'Sewa',                   status: 'absent' },
      { memberId: 'WBL-043', memberName: 'Chetan Mehta',        gender: 'male',   ageCategory: 'yuva',    jobTitle: 'Sanghchalak',            status: 'absent' },
      { memberId: 'WBL-044', memberName: 'Payal Verma',         gender: 'female', ageCategory: 'kishor',  jobTitle: 'Kishor(i)',              status: 'absent' },
      { memberId: 'WBL-045', memberName: 'Bhavesh Iyer',        gender: 'male',   ageCategory: 'tarun',   jobTitle: 'Prachaar',               status: 'absent' },
      { memberId: 'WBL-046', memberName: 'Chanchal Rao',        gender: 'female', ageCategory: 'tarun',   jobTitle: 'Sewa',                   status: 'absent' },
      { memberId: 'WBL-047', memberName: 'Dilip Pillai',        gender: 'male',   ageCategory: 'yuva',    jobTitle: 'Vyavestha',              status: 'absent' },
      { memberId: 'WBL-048', memberName: 'Falak Reddy',         gender: 'female', ageCategory: 'tarun',   jobTitle: 'Tarun(i)',               status: 'absent' },
      { memberId: 'WBL-049', memberName: 'Gopal Bose',          gender: 'male',   ageCategory: 'jyestha', jobTitle: 'Jyestha(a)',             status: 'absent' },
      { memberId: 'WBL-050', memberName: 'Harsha Trivedi',      gender: 'female', ageCategory: 'tarun',   jobTitle: 'Sewa',                   status: 'absent' },
      { memberId: 'WBL-051', memberName: 'Jayesh Kapoor',       gender: 'male',   ageCategory: 'tarun',   jobTitle: 'SSV',                    status: 'absent' },
      { memberId: 'WBL-052', memberName: 'Kamini Dixit',        gender: 'female', ageCategory: 'yuva',    jobTitle: 'Sewa',                   status: 'absent' },
      { memberId: 'WBL-053', memberName: 'Lalit Menon',         gender: 'male',   ageCategory: 'tarun',   jobTitle: 'Vistaar',                status: 'absent' },
      { memberId: 'WBL-054', memberName: 'Madhuri Saxena',      gender: 'female', ageCategory: 'tarun',   jobTitle: 'Sewa',                   status: 'absent' },
      { memberId: 'WBL-055', memberName: 'Naveen Pandey',       gender: 'male',   ageCategory: 'tarun',   jobTitle: 'Nidhi',                  status: 'absent' },
      { memberId: 'WBL-056', memberName: 'Nalini Mishra',       gender: 'female', ageCategory: 'yuva',    jobTitle: 'Sewa',                   status: 'absent' },
      { memberId: 'WBL-057', memberName: 'Omkar Tiwari',        gender: 'male',   ageCategory: 'tarun',   jobTitle: 'Shareerik',              status: 'absent' },
      { memberId: 'WBL-058', memberName: 'Padma Dubey',         gender: 'female', ageCategory: 'jyestha', jobTitle: 'Jyestha(a)',             status: 'absent' },
      { memberId: 'WBL-059', memberName: 'Prakash Banerjee',    gender: 'male',   ageCategory: 'yuva',    jobTitle: 'Karyawaha',              status: 'absent' },
      { memberId: 'WBL-060', memberName: 'Revati Agarwal',      gender: 'female', ageCategory: 'tarun',   jobTitle: 'Sewa',                   status: 'absent' },
      { memberId: 'WBL-061', memberName: 'Sanjeev Chatterjee',  gender: 'male',   ageCategory: 'yuva',    jobTitle: 'Mukhya Shikshak',        status: 'absent' },
      { memberId: 'WBL-062', memberName: 'Savitri Das',         gender: 'female', ageCategory: 'jyestha', jobTitle: 'Jyestha(a)',             status: 'absent' },
      { memberId: 'WBL-063', memberName: 'Tilak Srivastava',    gender: 'male',   ageCategory: 'tarun',   jobTitle: 'Sampark',                status: 'absent' },
      { memberId: 'WBL-064', memberName: 'Tanvi Roy',           gender: 'female', ageCategory: 'tarun',   jobTitle: 'Sewa',                   status: 'absent' },
      { memberId: 'WBL-065', memberName: 'Uday Ghosh',          gender: 'male',   ageCategory: 'tarun',   jobTitle: 'Karyalay',               status: 'absent' },
      { memberId: 'WBL-066', memberName: 'Urvashi Malhotra',    gender: 'female', ageCategory: 'tarun',   jobTitle: 'Tarun(i)',               status: 'absent' },
      { memberId: 'WBL-067', memberName: 'Vijay Khanna',        gender: 'male',   ageCategory: 'yuva',    jobTitle: 'Ghatnayak',              status: 'absent' },
      { memberId: 'WBL-068', memberName: 'Varsha Arora',        gender: 'female', ageCategory: 'tarun',   jobTitle: 'Sewa',                   status: 'absent' },
      { memberId: 'WBL-069', memberName: 'Yogendra Bhatia',     gender: 'male',   ageCategory: 'jyestha', jobTitle: 'Jyestha(a)',             status: 'absent' },
      { memberId: 'WBL-070', memberName: 'Yamini Sethi',        gender: 'female', ageCategory: 'tarun',   jobTitle: 'Sewa',                   status: 'absent' },
      { memberId: 'WBL-071', memberName: 'Aditya Chopra',       gender: 'male',   ageCategory: 'tarun',   jobTitle: 'Shikshak',               status: 'absent' },
      { memberId: 'WBL-072', memberName: 'Amita Anand',         gender: 'female', ageCategory: 'yuva',    jobTitle: 'Sewa',                   status: 'absent' },
      { memberId: 'WBL-073', memberName: 'Baldev Goel',         gender: 'male',   ageCategory: 'yuva',    jobTitle: 'Sampark',                status: 'absent' },
      { memberId: 'WBL-074', memberName: 'Bharati Hegde',       gender: 'female', ageCategory: 'tarun',   jobTitle: 'Sewa',                   status: 'absent' },
      { memberId: 'WBL-075', memberName: 'Chandresh Naik',      gender: 'male',   ageCategory: 'tarun',   jobTitle: 'Bauddhik',               status: 'absent' },
      { memberId: 'WBL-076', memberName: 'Charu Rathod',        gender: 'female', ageCategory: 'kishor',  jobTitle: 'Kishor(i)',              status: 'absent' },
      { memberId: 'WBL-077', memberName: 'Dhruv Samant',        gender: 'male',   ageCategory: 'shishu',  jobTitle: 'Shishu',                 status: 'absent' },
      { memberId: 'WBL-078', memberName: 'Deepmala Upadhyay',   gender: 'female', ageCategory: 'tarun',   jobTitle: 'Sewa',                   status: 'absent' },
      { memberId: 'WBL-079', memberName: 'Eknath Vyas',         gender: 'male',   ageCategory: 'jyestha', jobTitle: 'Jyestha(a)',             status: 'absent' },
      { memberId: 'WBL-080', memberName: 'Esha Sharma',         gender: 'female', ageCategory: 'tarun',   jobTitle: 'Tarun(i)',               status: 'absent' },
      { memberId: 'WBL-081', memberName: 'Girish Patel',        gender: 'male',   ageCategory: 'tarun',   jobTitle: 'Sampark',                status: 'absent' },
      { memberId: 'WBL-082', memberName: 'Gauri Kumar',         gender: 'female', ageCategory: 'yuva',    jobTitle: 'Sewa',                   status: 'absent' },
      { memberId: 'WBL-083', memberName: 'Hitesh Singh',        gender: 'male',   ageCategory: 'tarun',   jobTitle: 'Prachaar',               status: 'absent' },
      { memberId: 'WBL-084', memberName: 'Hansika Nair',        gender: 'female', ageCategory: 'kishor',  jobTitle: 'Kishor(i)',              status: 'absent' },
      { memberId: 'WBL-085', memberName: 'Ilesh Iyer',          gender: 'male',   ageCategory: 'tarun',   jobTitle: 'Nidhi',                  status: 'absent' },
      { memberId: 'WBL-086', memberName: 'Indumati Joshi',      gender: 'female', ageCategory: 'jyestha', jobTitle: 'Jyestha(a)',             status: 'absent' },
      { memberId: 'WBL-087', memberName: 'Jatin Mehta',         gender: 'male',   ageCategory: 'tarun',   jobTitle: 'SSV',                    status: 'absent' },
      { memberId: 'WBL-088', memberName: 'Janaki Gupta',        gender: 'female', ageCategory: 'yuva',    jobTitle: 'Sewa',                   status: 'absent' },
      { memberId: 'WBL-089', memberName: 'Kapil Verma',         gender: 'male',   ageCategory: 'tarun',   jobTitle: 'Shikshak',               status: 'absent' },
      { memberId: 'WBL-090', memberName: 'Kamakshi Desai',      gender: 'female', ageCategory: 'tarun',   jobTitle: 'Sewa',                   status: 'absent' },
      { memberId: 'WBL-091', memberName: 'Laxman Shah',         gender: 'male',   ageCategory: 'yuva',    jobTitle: 'Mukhya Shikshak',        status: 'absent' },
      { memberId: 'WBL-092', memberName: 'Lalitha Rao',         gender: 'female', ageCategory: 'yuva',    jobTitle: 'Sewa',                   status: 'absent' },
      { memberId: 'WBL-093', memberName: 'Madhav Pillai',       gender: 'male',   ageCategory: 'tarun',   jobTitle: 'Vistaar',                status: 'absent' },
      { memberId: 'WBL-094', memberName: 'Mrunal Bose',         gender: 'female', ageCategory: 'tarun',   jobTitle: 'Tarun(i)',               status: 'absent' },
      { memberId: 'WBL-095', memberName: 'Navin Trivedi',       gender: 'male',   ageCategory: 'tarun',   jobTitle: 'Karyalay',               status: 'absent' },
      { memberId: 'WBL-096', memberName: 'Namrata Kapoor',      gender: 'female', ageCategory: 'tarun',   jobTitle: 'Sewa',                   status: 'absent' },
      { memberId: 'WBL-097', memberName: 'Parth Dixit',         gender: 'male',   ageCategory: 'kishor',  jobTitle: 'Kishor(i)',              status: 'absent' },
      { memberId: 'WBL-098', memberName: 'Purnima Menon',       gender: 'female', ageCategory: 'yuva',    jobTitle: 'Sewa',                   status: 'absent' },
      { memberId: 'WBL-099', memberName: 'Ranjit Krishnan',     gender: 'male',   ageCategory: 'yuva',    jobTitle: 'Sampark',                status: 'absent' },
      { memberId: 'WBL-100', memberName: 'Ratna Reddy',         gender: 'female', ageCategory: 'tarun',   jobTitle: 'Sewa',                   status: 'absent' },
      { memberId: 'WBL-101', memberName: 'Siddharth Saxena',    gender: 'male',   ageCategory: 'tarun',   jobTitle: 'Bauddhik',               status: 'absent' },
      { memberId: 'WBL-102', memberName: 'Sharda Pandey',       gender: 'female', ageCategory: 'jyestha', jobTitle: 'Jyestha(a)',             status: 'absent' },
      { memberId: 'WBL-103', memberName: 'Trivikram Mishra',    gender: 'male',   ageCategory: 'yuva',    jobTitle: 'Karyawaha',              status: 'absent' },
      { memberId: 'WBL-104', memberName: 'Trupti Tiwari',       gender: 'female', ageCategory: 'tarun',   jobTitle: 'Sewa',                   status: 'absent' },
      { memberId: 'WBL-105', memberName: 'Ujjwal Dubey',        gender: 'male',   ageCategory: 'tarun',   jobTitle: 'Shareerik',              status: 'absent' },
      { memberId: 'WBL-106', memberName: 'Urmila Chaudhary',    gender: 'female', ageCategory: 'yuva',    jobTitle: 'Sewa',                   status: 'absent' },
      { memberId: 'WBL-107', memberName: 'Vishnu Banerjee',     gender: 'male',   ageCategory: 'yuva',    jobTitle: 'Sanghchalak',            status: 'absent' },
      { memberId: 'WBL-108', memberName: 'Vaidehi Agarwal',     gender: 'female', ageCategory: 'tarun',   jobTitle: 'Tarun(i)',               status: 'absent' },
      { memberId: 'WBL-109', memberName: 'Wasim Srivastava',    gender: 'male',   ageCategory: 'tarun',   jobTitle: 'SSV',                    status: 'absent' },
      { memberId: 'WBL-110', memberName: 'Yamuna Chatterjee',   gender: 'female', ageCategory: 'yuva',    jobTitle: 'Sewa',                   status: 'absent' },
      { memberId: 'WBL-111', memberName: 'Yuvraj Das',          gender: 'male',   ageCategory: 'kishor',  jobTitle: 'Kishor(i)',              status: 'absent' },
      { memberId: 'WBL-112', memberName: 'Zeenat Roy',          gender: 'female', ageCategory: 'tarun',   jobTitle: 'Sewa',                   status: 'absent' },
      { memberId: 'WBL-113', memberName: 'Aniket Ghosh',        gender: 'male',   ageCategory: 'tarun',   jobTitle: 'Sampark',                status: 'absent' },
      { memberId: 'WBL-114', memberName: 'Achala Malhotra',     gender: 'female', ageCategory: 'tarun',   jobTitle: 'Sewa',                   status: 'absent' },
      { memberId: 'WBL-115', memberName: 'Bharat Khanna',       gender: 'male',   ageCategory: 'yuva',    jobTitle: 'Ghatnayak',              status: 'absent' },
      { memberId: 'WBL-116', memberName: 'Bipasha Arora',       gender: 'female', ageCategory: 'tarun',   jobTitle: 'Sewa',                   status: 'absent' },
      { memberId: 'WBL-117', memberName: 'Cyrus Bhatia',        gender: 'male',   ageCategory: 'tarun',   jobTitle: 'Prachaar',               status: 'absent' },
      { memberId: 'WBL-118', memberName: 'Chandana Sethi',      gender: 'female', ageCategory: 'kishor',  jobTitle: 'Kishor(i)',              status: 'absent' },
      { memberId: 'WBL-119', memberName: 'Devraj Chopra',       gender: 'male',   ageCategory: 'yuva',    jobTitle: 'Mukhya Shikshak',        status: 'absent' },
      { memberId: 'WBL-120', memberName: 'Darshana Anand',      gender: 'female', ageCategory: 'tarun',   jobTitle: 'Sewa',                   status: 'absent' },
      { memberId: 'WBL-121', memberName: 'Eshan Goel',          gender: 'male',   ageCategory: 'shishu',  jobTitle: 'Shishu',                 status: 'absent' },
      { memberId: 'WBL-122', memberName: 'Eshita Hegde',        gender: 'female', ageCategory: 'tarun',   jobTitle: 'Sewa',                   status: 'absent' },
      { memberId: 'WBL-123', memberName: 'Faisal Naik',         gender: 'male',   ageCategory: 'tarun',   jobTitle: 'Vistaar',                status: 'absent' },
      { memberId: 'WBL-124', memberName: 'Gitanjali Yadav',     gender: 'female', ageCategory: 'yuva',    jobTitle: 'Hindu Sahitya Kendra',   status: 'absent' },
      { memberId: 'WBL-125', memberName: 'Gajanan Rathod',      gender: 'male',   ageCategory: 'yuva',    jobTitle: 'Sampark',                status: 'absent' },
      { memberId: 'WBL-126', memberName: 'Hemmalini Samant',    gender: 'female', ageCategory: 'jyestha', jobTitle: 'Jyestha(a)',             status: 'absent' },
      { memberId: 'WBL-127', memberName: 'Hardev Thakkar',      gender: 'male',   ageCategory: 'jyestha', jobTitle: 'Jyestha(a)',             status: 'absent' },
      { memberId: 'WBL-128', memberName: 'Ila Upadhyay',        gender: 'female', ageCategory: 'yuva',    jobTitle: 'Sewa',                   status: 'absent' },
      { memberId: 'WBL-129', memberName: 'Indrajit Vyas',       gender: 'male',   ageCategory: 'yuva',    jobTitle: 'Karyawaha',              status: 'absent' },
      { memberId: 'WBL-130', memberName: 'Jyoti Sharma',        gender: 'female', ageCategory: 'tarun',   jobTitle: 'Sewa',                   status: 'absent' },
      { memberId: 'WBL-131', memberName: 'Jeevan Patel',        gender: 'male',   ageCategory: 'tarun',   jobTitle: 'Bauddhik',               status: 'absent' },
      { memberId: 'WBL-132', memberName: 'Kanchan Kumar',       gender: 'female', ageCategory: 'tarun',   jobTitle: 'Tarun(i)',               status: 'absent' },
      { memberId: 'WBL-133', memberName: 'Kamlesh Singh',       gender: 'male',   ageCategory: 'yuva',    jobTitle: 'Vyavestha',              status: 'absent' },
      { memberId: 'WBL-134', memberName: 'Laleh Nair',          gender: 'female', ageCategory: 'tarun',   jobTitle: 'Sewa',                   status: 'absent' },
      { memberId: 'WBL-135', memberName: 'Lokesh Iyer',         gender: 'male',   ageCategory: 'tarun',   jobTitle: 'Shikshak',               status: 'absent' },
      { memberId: 'WBL-136', memberName: 'Meenakshi Joshi',     gender: 'female', ageCategory: 'yuva',    jobTitle: 'Sewa',                   status: 'absent' },
      { memberId: 'WBL-137', memberName: 'Milind Mehta',        gender: 'male',   ageCategory: 'tarun',   jobTitle: 'SSV',                    status: 'absent' },
      { memberId: 'WBL-138', memberName: 'Nirupama Gupta',      gender: 'female', ageCategory: 'tarun',   jobTitle: 'Sewa',                   status: 'absent' },
      { memberId: 'WBL-139', memberName: 'Nilesh Verma',        gender: 'male',   ageCategory: 'tarun',   jobTitle: 'Nidhi',                  status: 'absent' },
      { memberId: 'WBL-140', memberName: 'Ojasvini Desai',      gender: 'female', ageCategory: 'kishor',  jobTitle: 'Kishor(i)',              status: 'absent' },
      { memberId: 'WBL-141', memberName: 'Parth Shah',          gender: 'male',   ageCategory: 'kishor',  jobTitle: 'Kishor(i)',              status: 'absent' },
      { memberId: 'WBL-142', memberName: 'Prabha Rao',          gender: 'female', ageCategory: 'yuva',    jobTitle: 'Sewa',                   status: 'absent' },
      { memberId: 'WBL-143', memberName: 'Qadir Pillai',        gender: 'male',   ageCategory: 'tarun',   jobTitle: 'Sampark',                status: 'absent' },
      { memberId: 'WBL-144', memberName: 'Radha Bose',          gender: 'female', ageCategory: 'jyestha', jobTitle: 'Jyestha(a)',             status: 'absent' },
      { memberId: 'WBL-145', memberName: 'Rajiv Trivedi',       gender: 'male',   ageCategory: 'yuva',    jobTitle: 'Mukhya Shikshak',        status: 'absent' },
      { memberId: 'WBL-146', memberName: 'Rukmini Kapoor',      gender: 'female', ageCategory: 'yuva',    jobTitle: 'Sewa',                   status: 'absent' },
      { memberId: 'WBL-147', memberName: 'Santosh Dixit',       gender: 'male',   ageCategory: 'tarun',   jobTitle: 'Karyalay',               status: 'absent' },
      { memberId: 'WBL-148', memberName: 'Shailaja Menon',      gender: 'female', ageCategory: 'tarun',   jobTitle: 'Sewa',                   status: 'absent' },
      { memberId: 'WBL-149', memberName: 'Tejas Krishnan',      gender: 'male',   ageCategory: 'tarun',   jobTitle: 'Shareerik',              status: 'absent' },
      { memberId: 'WBL-150', memberName: 'Surekha Reddy',       gender: 'female', ageCategory: 'yuva',    jobTitle: 'Sewa',                   status: 'absent' },
      { memberId: 'WBL-151', memberName: 'Umang Saxena',        gender: 'male',   ageCategory: 'tarun',   jobTitle: 'Vistaar',                status: 'absent' },
      { memberId: 'WBL-152', memberName: 'Tripta Pandey',       gender: 'female', ageCategory: 'tarun',   jobTitle: 'Sewa',                   status: 'absent' },
      { memberId: 'WBL-153', memberName: 'Vasudev Mishra',      gender: 'male',   ageCategory: 'jyestha', jobTitle: 'Jyestha(a)',             status: 'absent' },
      { memberId: 'WBL-154', memberName: 'Vidya Tiwari',        gender: 'female', ageCategory: 'tarun',   jobTitle: 'Tarun(i)',               status: 'absent' },
      { memberId: 'WBL-155', memberName: 'Wirendra Dubey',      gender: 'male',   ageCategory: 'tarun',   jobTitle: 'Sankhya',                status: 'absent' },
      { memberId: 'WBL-156', memberName: 'Wasima Chaudhary',    gender: 'female', ageCategory: 'tarun',   jobTitle: 'Sewa',                   status: 'absent' },
      { memberId: 'WBL-157', memberName: 'Yash Banerjee',       gender: 'male',   ageCategory: 'kishor',  jobTitle: 'Kishor(i)',              status: 'absent' },
      { memberId: 'WBL-158', memberName: 'Yashoda Agarwal',     gender: 'female', ageCategory: 'yuva',    jobTitle: 'Sewa',                   status: 'absent' },
      { memberId: 'WBL-159', memberName: 'Zayd Srivastava',     gender: 'male',   ageCategory: 'tarun',   jobTitle: 'Prachaar',               status: 'absent' },
      { memberId: 'WBL-160', memberName: 'Zakia Chatterjee',    gender: 'female', ageCategory: 'tarun',   jobTitle: 'Sewa',                   status: 'absent' },
      { memberId: 'WBL-161', memberName: 'Abhishek Das',        gender: 'male',   ageCategory: 'tarun',   jobTitle: 'Bauddhik',               status: 'absent' },
      { memberId: 'WBL-162', memberName: 'Alpana Roy',          gender: 'female', ageCategory: 'tarun',   jobTitle: 'Sewa',                   status: 'absent' },
      { memberId: 'WBL-163', memberName: 'Bina Ghosh',          gender: 'female', ageCategory: 'yuva',    jobTitle: 'Sewa',                   status: 'absent' },
      { memberId: 'WBL-164', memberName: 'Birendra Malhotra',   gender: 'male',   ageCategory: 'yuva',    jobTitle: 'Sampark',                status: 'absent' },
      { memberId: 'WBL-165', memberName: 'Charulata Khanna',    gender: 'female', ageCategory: 'jyestha', jobTitle: 'Jyestha(a)',             status: 'absent' },
      { memberId: 'WBL-166', memberName: 'Chhaya Arora',        gender: 'female', ageCategory: 'tarun',   jobTitle: 'Sewa',                   status: 'absent' },
      { memberId: 'WBL-167', memberName: 'Damayanti Bhatia',    gender: 'female', ageCategory: 'yuva',    jobTitle: 'Hindu Sahitya Kendra',   status: 'absent' },
      { memberId: 'WBL-168', memberName: 'Dinesh Sethi',        gender: 'male',   ageCategory: 'tarun',   jobTitle: 'Shikshak',               status: 'absent' },
      { memberId: 'WBL-169', memberName: 'Eshwar Chopra',       gender: 'male',   ageCategory: 'yuva',    jobTitle: 'Karyawaha',              status: 'absent' },
      { memberId: 'WBL-170', memberName: 'Ekta Anand',          gender: 'female', ageCategory: 'tarun',   jobTitle: 'Tarun(i)',               status: 'absent' },
      { memberId: 'WBL-171', memberName: 'Farida Goel',         gender: 'female', ageCategory: 'tarun',   jobTitle: 'Sewa',                   status: 'absent' },
      { memberId: 'WBL-172', memberName: 'Falguni Hegde',       gender: 'female', ageCategory: 'kishor',  jobTitle: 'Kishor(i)',              status: 'absent' },
      { memberId: 'WBL-173', memberName: 'Gaurishankar Naik',   gender: 'male',   ageCategory: 'jyestha', jobTitle: 'Jyestha(a)',             status: 'absent' },
      { memberId: 'WBL-174', memberName: 'Gunjan Yadav',        gender: 'female', ageCategory: 'tarun',   jobTitle: 'Sewa',                   status: 'absent' },
      { memberId: 'WBL-175', memberName: 'Himani Rathod',       gender: 'female', ageCategory: 'tarun',   jobTitle: 'Sewa',                   status: 'absent' },
      { memberId: 'WBL-176', memberName: 'Harish Samant',       gender: 'male',   ageCategory: 'yuva',    jobTitle: 'Mukhya Shikshak',        status: 'absent' },
      { memberId: 'WBL-177', memberName: 'Imran Thakkar',       gender: 'male',   ageCategory: 'tarun',   jobTitle: 'SSV',                    status: 'absent' },
      { memberId: 'WBL-178', memberName: 'Ila Upadhyay',        gender: 'female', ageCategory: 'tarun',   jobTitle: 'Sewa',                   status: 'absent' },
      { memberId: 'WBL-179', memberName: 'Jitendra Vyas',       gender: 'male',   ageCategory: 'yuva',    jobTitle: 'Sanghchalak',            status: 'absent' },
      { memberId: 'WBL-180', memberName: 'Jasmin Sharma',       gender: 'female', ageCategory: 'tarun',   jobTitle: 'Sewa',                   status: 'absent' },
      { memberId: 'WBL-181', memberName: 'Krunal Patel',        gender: 'male',   ageCategory: 'tarun',   jobTitle: 'Vistaar',                status: 'absent' },
      { memberId: 'WBL-182', memberName: 'Komal Iyer',          gender: 'female', ageCategory: 'kishor',  jobTitle: 'Kishor(i)',              status: 'absent' },
      { memberId: 'WBL-183', memberName: 'Keyur Mehta',         gender: 'male',   ageCategory: 'tarun',   jobTitle: 'Nidhi',                  status: 'absent' },
      { memberId: 'WBL-184', memberName: 'Ketki Gupta',         gender: 'female', ageCategory: 'shishu',  jobTitle: 'Shishu',                 status: 'absent' },
      { memberId: 'WBL-185', memberName: 'Lavanya Verma',       gender: 'female', ageCategory: 'tarun',   jobTitle: 'Sewa',                   status: 'absent' },
      { memberId: 'WBL-186', memberName: 'Laxmi Desai',         gender: 'female', ageCategory: 'yuva',    jobTitle: 'Sewa',                   status: 'absent' },
      { memberId: 'WBL-187', memberName: 'Minal Shah',          gender: 'female', ageCategory: 'tarun',   jobTitle: 'Tarun(i)',               status: 'absent' },
      { memberId: 'WBL-188', memberName: 'Mahesh Rao',          gender: 'male',   ageCategory: 'yuva',    jobTitle: 'Ghatnayak',              status: 'absent' },
      { memberId: 'WBL-189', memberName: 'Neepa Pillai',        gender: 'female', ageCategory: 'tarun',   jobTitle: 'Sewa',                   status: 'absent' },
      { memberId: 'WBL-190', memberName: 'Neeraj Bose',         gender: 'male',   ageCategory: 'tarun',   jobTitle: 'Shareerik',              status: 'absent' },
      { memberId: 'WBL-191', memberName: 'Padmini Trivedi',     gender: 'female', ageCategory: 'jyestha', jobTitle: 'Jyestha(a)',             status: 'absent' },
      { memberId: 'WBL-192', memberName: 'Omvati Kapoor',       gender: 'female', ageCategory: 'jyestha', jobTitle: 'Jyestha(a)',             status: 'absent' },
      { memberId: 'WBL-193', memberName: 'Paresh Dixit',        gender: 'male',   ageCategory: 'tarun',   jobTitle: 'Karyalay',               status: 'absent' },
      { memberId: 'WBL-194', memberName: 'Parvati Menon',       gender: 'female', ageCategory: 'yuva',    jobTitle: 'Sewa',                   status: 'absent' },
    ],
  },
  {
    id: 'SES-002',
    title: 'Wembley Shakha — Weekly',
    activityCentre: 'Wembley Activity Centre',
    region: 'London & South East',
    town: 'Wembley',
    frequency: 'weekly',
    dayOfWeek: 4,
    startTime: '18:00',
    endTime:   '20:00',
    date: '2026-05-14',
    status: 'completed',
    totalExpected: 12,
    attendanceRecords: [
      { memberId: 'MBR-001', memberName: 'Arjun Sharma',   gender: 'male',   ageCategory: 'tarun', jobTitle: 'Karyawaha',         status: 'present', markedAt: '2026-05-14T18:04:00Z' },
      { memberId: 'MBR-006', memberName: 'Deepa Nair',     gender: 'female', ageCategory: 'tarun', jobTitle: 'Sewa',            status: 'absent'  },
      { memberId: 'MBR-009', memberName: 'Ravi Kumar',     gender: 'male',   ageCategory: 'tarun', jobTitle: 'Shikshak',          status: 'present', markedAt: '2026-05-14T18:07:00Z' },
      { memberId: 'MBR-010', memberName: 'Anita Desai',    gender: 'female', ageCategory: 'tarun', jobTitle: 'Sewa',            status: 'present', markedAt: '2026-05-14T18:09:00Z' },
      { memberId: 'MBR-011', memberName: 'Suresh Pillai',  gender: 'male',   ageCategory: 'tarun', jobTitle: 'Sampark',             status: 'present', markedAt: '2026-05-14T18:11:00Z' },
      { memberId: 'MBR-012', memberName: 'Meera Iyer',     gender: 'female', ageCategory: 'kishor',  jobTitle: 'Kishor(i)',     status: 'absent'  },
    ],
  },
  {
    id: 'SES-003',
    title: 'Wembley Shakha — Weekly',
    activityCentre: 'Wembley Activity Centre',
    region: 'London & South East',
    town: 'Wembley',
    frequency: 'weekly',
    dayOfWeek: 4,
    startTime: '18:00',
    endTime:   '20:00',
    date: '2026-05-21',
    status: 'completed',
    totalExpected: 12,
    attendanceRecords: [
      { memberId: 'MBR-001', memberName: 'Arjun Sharma',   gender: 'male',   ageCategory: 'tarun', jobTitle: 'Karyawaha',         status: 'present', markedAt: '2026-05-21T18:03:00Z' },
      { memberId: 'MBR-006', memberName: 'Deepa Nair',     gender: 'female', ageCategory: 'tarun', jobTitle: 'Sewa',            status: 'present', markedAt: '2026-05-21T18:06:00Z' },
      { memberId: 'MBR-009', memberName: 'Ravi Kumar',     gender: 'male',   ageCategory: 'tarun', jobTitle: 'Shikshak',          status: 'present', markedAt: '2026-05-21T18:08:00Z' },
      { memberId: 'MBR-010', memberName: 'Anita Desai',    gender: 'female', ageCategory: 'tarun', jobTitle: 'Sewa',            status: 'absent'  },
      { memberId: 'MBR-011', memberName: 'Suresh Pillai',  gender: 'male',   ageCategory: 'tarun', jobTitle: 'Sampark',             status: 'present', markedAt: '2026-05-21T18:10:00Z' },
      { memberId: 'MBR-012', memberName: 'Meera Iyer',     gender: 'female', ageCategory: 'kishor',  jobTitle: 'Kishor(i)',     status: 'present', markedAt: '2026-05-21T18:13:00Z' },
    ],
  },
  {
    id: 'SES-004',
    title: 'Wembley Shakha — Weekly',
    activityCentre: 'Wembley Activity Centre',
    region: 'London & South East',
    town: 'Wembley',
    frequency: 'weekly',
    dayOfWeek: 4,
    startTime: '18:00',
    endTime:   '20:00',
    date: '2026-05-28',
    status: 'scheduled',
    totalExpected: 12,
    attendanceRecords: [],
  },
  {
    id: 'SES-005',
    title: 'Wembley Shakha — Weekly',
    activityCentre: 'Wembley Activity Centre',
    region: 'London & South East',
    town: 'Wembley',
    frequency: 'weekly',
    dayOfWeek: 4,
    startTime: '18:00',
    endTime:   '20:00',
    date: '2026-06-04',
    status: 'scheduled',
    totalExpected: 12,
    attendanceRecords: [],
  },

  // ── Harrow Activity Centre ────────────────────────────────
  {
    id: 'SES-006',
    title: 'Harrow Shakha — Saturday',
    activityCentre: 'Harrow Activity Centre',
    region: 'London & South East',
    town: 'Harrow',
    frequency: 'weekly',
    dayOfWeek: 6,
    startTime: '10:00',
    endTime:   '12:00',
    date: '2026-05-03',
    status: 'completed',
    totalExpected: 8,
    attendanceRecords: [
      { memberId: 'MBR-002', memberName: 'Priya Patel',    gender: 'female', ageCategory: 'tarun', jobTitle: 'Sewa',            status: 'present', markedAt: '2026-05-03T10:04:00Z' },
      { memberId: 'MBR-007', memberName: 'Nikhil Joshi',   gender: 'male',   ageCategory: 'tarun', jobTitle: 'Sampark',             status: 'present', markedAt: '2026-05-03T10:06:00Z' },
      { memberId: 'MBR-013', memberName: 'Kavya Reddy',    gender: 'female', ageCategory: 'kishor',  jobTitle: 'Kishor(i)',     status: 'absent'  },
      { memberId: 'MBR-014', memberName: 'Arun Verma',     gender: 'male',   ageCategory: 'tarun', jobTitle: 'Shikshak',          status: 'present', markedAt: '2026-05-03T10:09:00Z' },
    ],
  },
  {
    id: 'SES-007',
    title: 'Harrow Shakha — Saturday',
    activityCentre: 'Harrow Activity Centre',
    region: 'London & South East',
    town: 'Harrow',
    frequency: 'weekly',
    dayOfWeek: 6,
    startTime: '10:00',
    endTime:   '12:00',
    date: '2026-05-10',
    status: 'completed',
    totalExpected: 8,
    attendanceRecords: [
      { memberId: 'MBR-002', memberName: 'Priya Patel',    gender: 'female', ageCategory: 'tarun', jobTitle: 'Sewa',            status: 'absent'  },
      { memberId: 'MBR-007', memberName: 'Nikhil Joshi',   gender: 'male',   ageCategory: 'tarun', jobTitle: 'Sampark',             status: 'present', markedAt: '2026-05-10T10:05:00Z' },
      { memberId: 'MBR-013', memberName: 'Kavya Reddy',    gender: 'female', ageCategory: 'kishor',  jobTitle: 'Kishor(i)',     status: 'present', markedAt: '2026-05-10T10:07:00Z' },
      { memberId: 'MBR-014', memberName: 'Arun Verma',     gender: 'male',   ageCategory: 'tarun', jobTitle: 'Shikshak',          status: 'present', markedAt: '2026-05-10T10:10:00Z' },
    ],
  },
  {
    id: 'SES-008',
    title: 'Harrow Shakha — Saturday',
    activityCentre: 'Harrow Activity Centre',
    region: 'London & South East',
    town: 'Harrow',
    frequency: 'weekly',
    dayOfWeek: 6,
    startTime: '10:00',
    endTime:   '12:00',
    date: '2026-05-17',
    status: 'completed',
    totalExpected: 8,
    attendanceRecords: [
      { memberId: 'MBR-002', memberName: 'Priya Patel',    gender: 'female', ageCategory: 'tarun', jobTitle: 'Sewa',            status: 'present', markedAt: '2026-05-17T10:03:00Z' },
      { memberId: 'MBR-007', memberName: 'Nikhil Joshi',   gender: 'male',   ageCategory: 'tarun', jobTitle: 'Sampark',             status: 'present', markedAt: '2026-05-17T10:05:00Z' },
      { memberId: 'MBR-013', memberName: 'Kavya Reddy',    gender: 'female', ageCategory: 'kishor',  jobTitle: 'Kishor(i)',     status: 'present', markedAt: '2026-05-17T10:08:00Z' },
      { memberId: 'MBR-014', memberName: 'Arun Verma',     gender: 'male',   ageCategory: 'tarun', jobTitle: 'Shikshak',          status: 'absent'  },
    ],
  },
  {
    id: 'SES-009',
    title: 'Harrow Shakha — Saturday',
    activityCentre: 'Harrow Activity Centre',
    region: 'London & South East',
    town: 'Harrow',
    frequency: 'weekly',
    dayOfWeek: 6,
    startTime: '10:00',
    endTime:   '12:00',
    date: '2026-05-24',
    status: 'scheduled',
    totalExpected: 8,
    attendanceRecords: [],
  },
  {
    id: 'SES-010',
    title: 'Harrow Shakha — Saturday',
    activityCentre: 'Harrow Activity Centre',
    region: 'London & South East',
    town: 'Harrow',
    frequency: 'weekly',
    dayOfWeek: 6,
    startTime: '10:00',
    endTime:   '12:00',
    date: '2026-05-31',
    status: 'scheduled',
    totalExpected: 8,
    attendanceRecords: [],
  },

  // ── Birmingham East Activity Centre ───────────────────────
  {
    id: 'SES-011',
    title: 'Birmingham East Shakha',
    activityCentre: 'Birmingham East Activity Centre',
    region: 'Midlands',
    town: 'Birmingham',
    frequency: 'weekly',
    dayOfWeek: 0,
    startTime: '11:00',
    endTime:   '13:00',
    date: '2026-05-04',
    status: 'completed',
    totalExpected: 10,
    attendanceRecords: [
      { memberId: 'MBR-003', memberName: 'Rahul Mehta',    gender: 'male',   ageCategory: 'tarun', jobTitle: 'Mukhya Shikshak',  status: 'present', markedAt: '2026-05-04T11:02:00Z' },
      { memberId: 'MBR-004', memberName: 'Sneha Gupta',    gender: 'female', ageCategory: 'kishor',  jobTitle: 'Kishor(i)',     status: 'present', markedAt: '2026-05-04T11:05:00Z' },
      { memberId: 'MBR-015', memberName: 'Kiran Bose',     gender: 'male',   ageCategory: 'tarun', jobTitle: 'Sampark',             status: 'absent'  },
      { memberId: 'MBR-016', memberName: 'Pooja Trivedi',  gender: 'female', ageCategory: 'tarun', jobTitle: 'Sewa',            status: 'present', markedAt: '2026-05-04T11:07:00Z' },
    ],
  },
  {
    id: 'SES-012',
    title: 'Birmingham East Shakha',
    activityCentre: 'Birmingham East Activity Centre',
    region: 'Midlands',
    town: 'Birmingham',
    frequency: 'weekly',
    dayOfWeek: 0,
    startTime: '11:00',
    endTime:   '13:00',
    date: '2026-05-11',
    status: 'completed',
    totalExpected: 10,
    attendanceRecords: [
      { memberId: 'MBR-003', memberName: 'Rahul Mehta',    gender: 'male',   ageCategory: 'tarun', jobTitle: 'Mukhya Shikshak',  status: 'present', markedAt: '2026-05-11T11:03:00Z' },
      { memberId: 'MBR-004', memberName: 'Sneha Gupta',    gender: 'female', ageCategory: 'kishor',  jobTitle: 'Kishor(i)',     status: 'absent'  },
      { memberId: 'MBR-015', memberName: 'Kiran Bose',     gender: 'male',   ageCategory: 'tarun', jobTitle: 'Sampark',             status: 'present', markedAt: '2026-05-11T11:06:00Z' },
      { memberId: 'MBR-016', memberName: 'Pooja Trivedi',  gender: 'female', ageCategory: 'tarun', jobTitle: 'Sewa',            status: 'present', markedAt: '2026-05-11T11:08:00Z' },
    ],
  },
  {
    id: 'SES-013',
    title: 'Birmingham East Shakha',
    activityCentre: 'Birmingham East Activity Centre',
    region: 'Midlands',
    town: 'Birmingham',
    frequency: 'weekly',
    dayOfWeek: 0,
    startTime: '11:00',
    endTime:   '13:00',
    date: '2026-05-18',
    status: 'completed',
    totalExpected: 10,
    attendanceRecords: [
      { memberId: 'MBR-003', memberName: 'Rahul Mehta',    gender: 'male',   ageCategory: 'tarun', jobTitle: 'Mukhya Shikshak',  status: 'absent'  },
      { memberId: 'MBR-004', memberName: 'Sneha Gupta',    gender: 'female', ageCategory: 'kishor',  jobTitle: 'Kishor(i)',     status: 'present', markedAt: '2026-05-18T11:04:00Z' },
      { memberId: 'MBR-015', memberName: 'Kiran Bose',     gender: 'male',   ageCategory: 'tarun', jobTitle: 'Sampark',             status: 'present', markedAt: '2026-05-18T11:06:00Z' },
      { memberId: 'MBR-016', memberName: 'Pooja Trivedi',  gender: 'female', ageCategory: 'tarun', jobTitle: 'Sewa',            status: 'present', markedAt: '2026-05-18T11:09:00Z' },
    ],
  },
  {
    id: 'SES-014',
    title: 'Birmingham East Shakha',
    activityCentre: 'Birmingham East Activity Centre',
    region: 'Midlands',
    town: 'Birmingham',
    frequency: 'weekly',
    dayOfWeek: 0,
    startTime: '11:00',
    endTime:   '13:00',
    date: '2026-05-25',
    status: 'scheduled',
    totalExpected: 10,
    attendanceRecords: [],
  },

  // ── Manchester Central ────────────────────────────────────
  {
    id: 'SES-015',
    title: 'Manchester Shakha — Thursday',
    activityCentre: 'Manchester Central Activity Centre',
    region: 'North West',
    town: 'Manchester',
    frequency: 'weekly',
    dayOfWeek: 4,
    startTime: '19:00',
    endTime:   '21:00',
    date: '2026-05-07',
    status: 'completed',
    totalExpected: 9,
    attendanceRecords: [
      { memberId: 'MBR-005', memberName: 'Vikram Singh',   gender: 'male',   ageCategory: 'tarun', jobTitle: 'Ghatnayak',   status: 'present', markedAt: '2026-05-07T19:02:00Z' },
      { memberId: 'MBR-008', memberName: 'Sonia Shah',     gender: 'female', ageCategory: 'tarun', jobTitle: 'Sewa',            status: 'present', markedAt: '2026-05-07T19:04:00Z' },
      { memberId: 'MBR-017', memberName: 'Amit Rao',       gender: 'male',   ageCategory: 'tarun', jobTitle: 'Shikshak',          status: 'absent'  },
    ],
  },
  {
    id: 'SES-016',
    title: 'Manchester Shakha — Thursday',
    activityCentre: 'Manchester Central Activity Centre',
    region: 'North West',
    town: 'Manchester',
    frequency: 'weekly',
    dayOfWeek: 4,
    startTime: '19:00',
    endTime:   '21:00',
    date: '2026-05-14',
    status: 'completed',
    totalExpected: 9,
    attendanceRecords: [
      { memberId: 'MBR-005', memberName: 'Vikram Singh',   gender: 'male',   ageCategory: 'tarun', jobTitle: 'Ghatnayak',   status: 'absent'  },
      { memberId: 'MBR-008', memberName: 'Sonia Shah',     gender: 'female', ageCategory: 'tarun', jobTitle: 'Sewa',            status: 'present', markedAt: '2026-05-14T19:05:00Z' },
      { memberId: 'MBR-017', memberName: 'Amit Rao',       gender: 'male',   ageCategory: 'tarun', jobTitle: 'Shikshak',          status: 'present', markedAt: '2026-05-14T19:07:00Z' },
    ],
  },
  {
    id: 'SES-017',
    title: 'Manchester Shakha — Thursday',
    activityCentre: 'Manchester Central Activity Centre',
    region: 'North West',
    town: 'Manchester',
    frequency: 'weekly',
    dayOfWeek: 4,
    startTime: '19:00',
    endTime:   '21:00',
    date: '2026-05-21',
    status: 'completed',
    totalExpected: 9,
    attendanceRecords: [
      { memberId: 'MBR-005', memberName: 'Vikram Singh',   gender: 'male',   ageCategory: 'tarun', jobTitle: 'Ghatnayak',   status: 'present', markedAt: '2026-05-21T19:01:00Z' },
      { memberId: 'MBR-008', memberName: 'Sonia Shah',     gender: 'female', ageCategory: 'tarun', jobTitle: 'Sewa',            status: 'present', markedAt: '2026-05-21T19:03:00Z' },
      { memberId: 'MBR-017', memberName: 'Amit Rao',       gender: 'male',   ageCategory: 'tarun', jobTitle: 'Shikshak',          status: 'present', markedAt: '2026-05-21T19:06:00Z' },
    ],
  },
  {
    id: 'SES-018',
    title: 'Manchester Shakha — Thursday',
    activityCentre: 'Manchester Central Activity Centre',
    region: 'North West',
    town: 'Manchester',
    frequency: 'weekly',
    dayOfWeek: 4,
    startTime: '19:00',
    endTime:   '21:00',
    date: '2026-05-28',
    status: 'scheduled',
    totalExpected: 9,
    attendanceRecords: [],
  },

  // ── Leeds North — Fortnightly ─────────────────────────────
  {
    id: 'SES-019',
    title: 'Leeds Shakha — Fortnightly',
    activityCentre: 'Leeds North Activity Centre',
    region: 'Yorkshire & Humber',
    town: 'Leeds',
    frequency: 'fortnightly',
    dayOfWeek: 6,
    startTime: '14:00',
    endTime:   '16:00',
    date: '2026-05-09',
    status: 'completed',
    totalExpected: 7,
    attendanceRecords: [
      { memberId: 'MBR-018', memberName: 'Deepak Sharma',  gender: 'male',   ageCategory: 'tarun', jobTitle: 'Karyawaha',         status: 'present', markedAt: '2026-05-09T14:03:00Z' },
      { memberId: 'MBR-019', memberName: 'Nisha Kapoor',   gender: 'female', ageCategory: 'tarun', jobTitle: 'Sewa',            status: 'present', markedAt: '2026-05-09T14:06:00Z' },
      { memberId: 'MBR-020', memberName: 'Rohit Dixit',    gender: 'male',   ageCategory: 'kishor',  jobTitle: 'Kishor(i)',     status: 'absent'  },
    ],
  },
  {
    id: 'SES-020',
    title: 'Leeds Shakha — Fortnightly',
    activityCentre: 'Leeds North Activity Centre',
    region: 'Yorkshire & Humber',
    town: 'Leeds',
    frequency: 'fortnightly',
    dayOfWeek: 6,
    startTime: '14:00',
    endTime:   '16:00',
    date: '2026-05-23',
    status: 'completed',
    totalExpected: 7,
    attendanceRecords: [
      { memberId: 'MBR-018', memberName: 'Deepak Sharma',  gender: 'male',   ageCategory: 'tarun', jobTitle: 'Karyawaha',         status: 'present', markedAt: '2026-05-23T14:02:00Z' },
      { memberId: 'MBR-019', memberName: 'Nisha Kapoor',   gender: 'female', ageCategory: 'tarun', jobTitle: 'Sewa',            status: 'absent'  },
      { memberId: 'MBR-020', memberName: 'Rohit Dixit',    gender: 'male',   ageCategory: 'kishor',  jobTitle: 'Kishor(i)',     status: 'present', markedAt: '2026-05-23T14:05:00Z' },
    ],
  },
  {
    id: 'SES-021',
    title: 'Leeds Shakha — Fortnightly',
    activityCentre: 'Leeds North Activity Centre',
    region: 'Yorkshire & Humber',
    town: 'Leeds',
    frequency: 'fortnightly',
    dayOfWeek: 6,
    startTime: '14:00',
    endTime:   '16:00',
    date: '2026-06-06',
    status: 'scheduled',
    totalExpected: 7,
    attendanceRecords: [],
  },

  // ── Edinburgh — One-off special session ───────────────────
  {
    id: 'SES-022',
    title: 'Edinburgh — Special Yoga Session',
    activityCentre: 'Edinburgh Activity Centre',
    region: 'Scotland',
    town: 'Edinburgh',
    frequency: 'one-off',
    dayOfWeek: 0,
    startTime: '10:00',
    endTime:   '12:30',
    date: '2026-05-19',
    status: 'completed',
    totalExpected: 15,
    attendanceRecords: [
      { memberId: 'MBR-021', memberName: 'Rajan Menon',    gender: 'male',   ageCategory: 'tarun', jobTitle: 'Mukhya Shikshak',  status: 'present', markedAt: '2026-05-19T10:02:00Z' },
      { memberId: 'MBR-022', memberName: 'Leela Nambiar',  gender: 'female', ageCategory: 'tarun', jobTitle: 'Sewa',            status: 'present', markedAt: '2026-05-19T10:04:00Z' },
      { memberId: 'MBR-023', memberName: 'Suraj Pillai',   gender: 'male',   ageCategory: 'kishor',  jobTitle: 'Kishor(i)',     status: 'absent'  },
      { memberId: 'MBR-024', memberName: 'Gita Krishnan',  gender: 'female', ageCategory: 'tarun', jobTitle: 'Sewa',            status: 'present', markedAt: '2026-05-19T10:07:00Z' },
    ],
  },

  // ── June sessions ─────────────────────────────────────────
  // April attendance log samples
  {
    id: 'SES-026',
    title: 'Leeds Shakha - Saturday',
    activityCentre: 'Leeds North Activity Centre',
    region: 'Yorkshire & Humber',
    town: 'Leeds',
    shakhaType: 'Milan',
    frequency: 'weekly',
    dayOfWeek: 6,
    startTime: '14:00',
    endTime: '16:00',
    date: '2026-04-04',
    status: 'completed',
    totalExpected: 4,
    attendanceRecords: [
      { memberId: 'MBR-018', memberName: 'Deepak Sharma', gender: 'male', ageCategory: 'tarun', jobTitle: 'Karyawaha', status: 'present', markedAt: '2026-04-04T14:02:00Z' },
      { memberId: 'MBR-019', memberName: 'Nisha Kapoor', gender: 'female', ageCategory: 'tarun', jobTitle: 'Sewa', status: 'present', markedAt: '2026-04-04T14:04:00Z' },
      { memberId: 'MBR-020', memberName: 'Rohit Dixit', gender: 'male', ageCategory: 'kishor', jobTitle: 'Kishor(i)', status: 'absent' },
      { memberId: 'MBR-008', memberName: 'Sonia Shah', gender: 'female', ageCategory: 'tarun', jobTitle: 'Sewa', status: 'present', markedAt: '2026-04-04T14:07:00Z' },
    ],
  },
  {
    id: 'SES-027',
    title: 'Birmingham Parivaar Shakha - Saturday',
    activityCentre: 'Birmingham East Activity Centre',
    region: 'Midlands',
    town: 'Birmingham',
    shakhaType: 'Parivaar Shakha',
    frequency: 'weekly',
    dayOfWeek: 6,
    startTime: '10:00',
    endTime: '12:00',
    date: '2026-04-11',
    status: 'completed',
    totalExpected: 4,
    attendanceRecords: [
      { memberId: 'MBR-003', memberName: 'Rahul Mehta', gender: 'male', ageCategory: 'tarun', jobTitle: 'Mukhya Shikshak', status: 'present', markedAt: '2026-04-11T10:02:00Z' },
      { memberId: 'MBR-004', memberName: 'Sneha Gupta', gender: 'female', ageCategory: 'kishor', jobTitle: 'Kishor(i)', status: 'present', markedAt: '2026-04-11T10:05:00Z' },
      { memberId: 'MBR-015', memberName: 'Kiran Bose', gender: 'male', ageCategory: 'tarun', jobTitle: 'Sampark', status: 'absent' },
      { memberId: 'MBR-016', memberName: 'Pooja Trivedi', gender: 'female', ageCategory: 'tarun', jobTitle: 'Sewa', status: 'present', markedAt: '2026-04-11T10:08:00Z' },
    ],
  },
  {
    id: 'SES-028',
    title: 'Wembley Shakha - Saturday',
    activityCentre: 'Wembley Activity Centre',
    region: 'London & South East',
    town: 'Wembley',
    shakhaType: 'Swayamsevak Shakha',
    frequency: 'weekly',
    dayOfWeek: 6,
    startTime: '17:00',
    endTime: '19:00',
    date: '2026-04-18',
    status: 'completed',
    totalExpected: 4,
    attendanceRecords: [
      { memberId: 'MBR-001', memberName: 'Arjun Sharma', gender: 'male', ageCategory: 'tarun', jobTitle: 'Karyawaha', status: 'present', markedAt: '2026-04-18T17:02:00Z' },
      { memberId: 'MBR-006', memberName: 'Deepa Nair', gender: 'female', ageCategory: 'tarun', jobTitle: 'Sewa', status: 'present', markedAt: '2026-04-18T17:04:00Z' },
      { memberId: 'MBR-010', memberName: 'Anita Desai', gender: 'female', ageCategory: 'tarun', jobTitle: 'Sewa', status: 'absent' },
      { memberId: 'MBR-012', memberName: 'Meera Iyer', gender: 'female', ageCategory: 'kishor', jobTitle: 'Kishor(i)', status: 'present', markedAt: '2026-04-18T17:08:00Z' },
    ],
  },

  // June attendance log samples, focused on Friday and Saturday
  {
    id: 'SES-029',
    title: 'Manchester Sewa Shakha - Friday',
    activityCentre: 'Manchester Central Activity Centre',
    region: 'North West',
    town: 'Manchester',
    shakhaType: 'Sewa Shakha',
    frequency: 'weekly',
    dayOfWeek: 5,
    startTime: '19:00',
    endTime: '21:00',
    date: '2026-06-05',
    status: 'completed',
    totalExpected: 3,
    attendanceRecords: [
      { memberId: 'MBR-005', memberName: 'Vikram Singh', gender: 'male', ageCategory: 'tarun', jobTitle: 'Ghatnayak', status: 'present', markedAt: '2026-06-05T19:03:00Z' },
      { memberId: 'MBR-008', memberName: 'Sonia Shah', gender: 'female', ageCategory: 'tarun', jobTitle: 'Sewa', status: 'present', markedAt: '2026-06-05T19:05:00Z' },
      { memberId: 'MBR-017', memberName: 'Amit Rao', gender: 'male', ageCategory: 'tarun', jobTitle: 'Shikshak', status: 'absent' },
    ],
  },
  {
    id: 'SES-030',
    title: 'Leeds Milan - Saturday',
    activityCentre: 'Leeds North Activity Centre',
    region: 'Yorkshire & Humber',
    town: 'Leeds',
    shakhaType: 'Milan',
    frequency: 'fortnightly',
    dayOfWeek: 6,
    startTime: '14:00',
    endTime: '16:00',
    date: '2026-06-06',
    status: 'completed',
    totalExpected: 2,
    attendanceRecords: [
      { memberId: 'MBR-018', memberName: 'Deepak Sharma', gender: 'male', ageCategory: 'tarun', jobTitle: 'Karyawaha', status: 'present', markedAt: '2026-06-06T14:02:00Z' },
      { memberId: 'MBR-019', memberName: 'Nisha Kapoor', gender: 'female', ageCategory: 'tarun', jobTitle: 'Sewa', status: 'present', markedAt: '2026-06-06T14:05:00Z' },
    ],
  },

  {
    id: 'SES-023',
    title: 'Wembley Shakha — Weekly',
    activityCentre: 'Wembley Activity Centre',
    region: 'London & South East',
    town: 'Wembley',
    frequency: 'weekly',
    dayOfWeek: 4,
    startTime: '18:00',
    endTime:   '20:00',
    date: '2026-06-11',
    status: 'scheduled',
    totalExpected: 12,
    attendanceRecords: [],
  },
  {
    id: 'SES-024',
    title: 'Birmingham East Shakha',
    activityCentre: 'Birmingham East Activity Centre',
    region: 'Midlands',
    town: 'Birmingham',
    frequency: 'weekly',
    dayOfWeek: 0,
    startTime: '11:00',
    endTime:   '13:00',
    date: '2026-06-01',
    status: 'scheduled',
    totalExpected: 10,
    attendanceRecords: [],
  },
  {
    id: 'SES-025',
    title: 'Manchester Shakha — Thursday',
    activityCentre: 'Manchester Central Activity Centre',
    region: 'North West',
    town: 'Manchester',
    frequency: 'weekly',
    dayOfWeek: 4,
    startTime: '19:00',
    endTime:   '21:00',
    date: '2026-06-04',
    status: 'scheduled',
    totalExpected: 9,
    attendanceRecords: [],
  },
];
