// ─────────────────────────────────────────────────────────────
// HSS UK Membership Management System — Logs Mock Data
// ─────────────────────────────────────────────────────────────

// ── Interfaces ────────────────────────────────────────────────

export interface LoginLog {
  id: string;
  userName: string;
  email: string;
  role: string;
  loginTime: string;
  logoutTime: string | null;
  ipAddress: string;
  device: string;
  browser: string;
  os: string;
  status: 'Success' | 'Failed';
  failureReason?: string;
  location: string;
  sessionDuration?: string;
}

export interface AuditLog {
  id: string;
  user: string;
  module: string;
  actionType: 'Create' | 'Update' | 'Delete' | 'Status Change' | 'Import' | 'Export' | 'Permission Update';
  recordName: string;
  recordId: string;
  description: string;
  timestamp: string;
  ipAddress: string;
  details: {
    before?: any;
    after?: any;
    changedFields?: string[];
  };
}

export interface APILog {
  id: string;
  apiName: string;
  endpoint: string;
  method: 'GET' | 'POST' | 'PUT' | 'DELETE' | 'PATCH';
  status: number;
  requestTime: string;
  responseTime: string; // duration in ms
  user: string;
  requestPayload: string;
  responsePayload: string;
  headers: Record<string, string>;
}

export interface EmailLog {
  id: string;
  recipientName: string;
  recipientEmail: string;
  templateName: string;
  subject: string;
  sentAt: string;
  status: 'Delivered' | 'Failed' | 'Sent' | 'Bounced';
  triggeredBy: string;
  failureReason?: string;
  contentPreview: string;
}

// ── Login Logs ────────────────────────────────────────────────
// 20 entries — real HSS admins, UK locations, May 2026
export const mockLoginLogs: LoginLog[] = [
  {
    id: 'LOG-001',
    userName: 'John Doe',
    email: 'john.doe@hss.org.uk',
    role: 'Super Admin',
    loginTime: '2026-05-30T08:28:00Z',
    logoutTime: null,
    ipAddress: '82.132.201.14',
    device: 'MacBook Pro 14"',
    browser: 'Chrome 124.0',
    os: 'macOS 14.4',
    status: 'Success',
    location: 'London, UK',
    sessionDuration: 'Active',
  },
  {
    id: 'LOG-002',
    userName: 'Sarah Smith',
    email: 'sarah.smith@hss.org.uk',
    role: 'Admin',
    loginTime: '2026-05-30T09:12:00Z',
    logoutTime: '2026-05-30T13:45:00Z',
    ipAddress: '86.143.56.22',
    device: 'Windows PC',
    browser: 'Edge 124.0',
    os: 'Windows 11',
    status: 'Success',
    location: 'Birmingham, UK',
    sessionDuration: '4h 33m',
  },
  {
    id: 'LOG-003',
    userName: 'Priya Patel',
    email: 'priya.patel@hss.org.uk',
    role: 'Admin',
    loginTime: '2026-05-30T07:44:00Z',
    logoutTime: '2026-05-30T12:00:00Z',
    ipAddress: '81.107.44.78',
    device: 'MacBook Air',
    browser: 'Safari 17.4',
    os: 'macOS 14.3',
    status: 'Success',
    location: 'Manchester, UK',
    sessionDuration: '4h 16m',
  },
  {
    id: 'LOG-004',
    userName: 'Unknown',
    email: 'admin@hss.org.uk',
    role: 'None',
    loginTime: '2026-05-30T03:17:00Z',
    logoutTime: null,
    ipAddress: '45.142.212.100',
    device: 'Unknown Device',
    browser: 'Python Requests 2.31',
    os: 'Linux',
    status: 'Failed',
    failureReason: 'Invalid password (3 attempts)',
    location: 'Unknown — VPN detected',
  },
  {
    id: 'LOG-005',
    userName: 'Michael Kumar',
    email: 'michael.kumar@hss.org.uk',
    role: 'Editor',
    loginTime: '2026-05-29T16:22:00Z',
    logoutTime: '2026-05-29T18:05:00Z',
    ipAddress: '86.156.78.90',
    device: 'Dell XPS 15',
    browser: 'Firefox 125.0',
    os: 'Windows 11',
    status: 'Success',
    location: 'Leeds, UK',
    sessionDuration: '1h 43m',
  },
  {
    id: 'LOG-006',
    userName: 'Rahul Gupta',
    email: 'rahul.gupta@hss.org.uk',
    role: 'Admin',
    loginTime: '2026-05-29T09:55:00Z',
    logoutTime: '2026-05-29T17:30:00Z',
    ipAddress: '217.155.32.48',
    device: 'iPhone 15 Pro',
    browser: 'Safari Mobile 17.4',
    os: 'iOS 17.4',
    status: 'Success',
    location: 'Glasgow, UK',
    sessionDuration: '7h 35m',
  },
  {
    id: 'LOG-007',
    userName: 'Sunita Sharma',
    email: 'sunita.sharma@hss.org.uk',
    role: 'Editor',
    loginTime: '2026-05-29T11:30:00Z',
    logoutTime: null,
    ipAddress: '81.109.23.55',
    device: 'iPad Pro',
    browser: 'Safari Mobile 17.4',
    os: 'iPadOS 17.4',
    status: 'Failed',
    failureReason: 'Incorrect OTP entered',
    location: 'Leicester, UK',
  },
  {
    id: 'LOG-008',
    userName: 'Sunita Sharma',
    email: 'sunita.sharma@hss.org.uk',
    role: 'Editor',
    loginTime: '2026-05-29T11:36:00Z',
    logoutTime: '2026-05-29T14:20:00Z',
    ipAddress: '81.109.23.55',
    device: 'iPad Pro',
    browser: 'Safari Mobile 17.4',
    os: 'iPadOS 17.4',
    status: 'Success',
    location: 'Leicester, UK',
    sessionDuration: '2h 44m',
  },
  {
    id: 'LOG-009',
    userName: 'John Doe',
    email: 'john.doe@hss.org.uk',
    role: 'Super Admin',
    loginTime: '2026-05-28T08:10:00Z',
    logoutTime: '2026-05-28T17:55:00Z',
    ipAddress: '82.132.201.14',
    device: 'MacBook Pro 14"',
    browser: 'Chrome 124.0',
    os: 'macOS 14.4',
    status: 'Success',
    location: 'London, UK',
    sessionDuration: '9h 45m',
  },
  {
    id: 'LOG-010',
    userName: 'David Mehta',
    email: 'david.mehta@hss.org.uk',
    role: 'Editor',
    loginTime: '2026-05-28T13:00:00Z',
    logoutTime: '2026-05-28T16:30:00Z',
    ipAddress: '80.229.55.12',
    device: 'Windows PC',
    browser: 'Chrome 124.0',
    os: 'Windows 10',
    status: 'Success',
    location: 'Cardiff, UK',
    sessionDuration: '3h 30m',
  },
  {
    id: 'LOG-011',
    userName: 'Unknown',
    email: 'superadmin@hss.org.uk',
    role: 'None',
    loginTime: '2026-05-27T23:41:00Z',
    logoutTime: null,
    ipAddress: '185.220.101.47',
    device: 'Unknown Device',
    browser: 'Curl 8.0',
    os: 'Linux',
    status: 'Failed',
    failureReason: 'Account locked after 5 failed attempts',
    location: 'Unknown — Tor Exit Node',
  },
  {
    id: 'LOG-012',
    userName: 'Sarah Smith',
    email: 'sarah.smith@hss.org.uk',
    role: 'Admin',
    loginTime: '2026-05-27T08:58:00Z',
    logoutTime: '2026-05-27T17:10:00Z',
    ipAddress: '86.143.56.22',
    device: 'Windows PC',
    browser: 'Edge 124.0',
    os: 'Windows 11',
    status: 'Success',
    location: 'Birmingham, UK',
    sessionDuration: '8h 12m',
  },
  {
    id: 'LOG-013',
    userName: 'Priya Patel',
    email: 'priya.patel@hss.org.uk',
    role: 'Admin',
    loginTime: '2026-05-26T08:30:00Z',
    logoutTime: '2026-05-26T12:45:00Z',
    ipAddress: '81.107.44.78',
    device: 'MacBook Air',
    browser: 'Safari 17.4',
    os: 'macOS 14.3',
    status: 'Failed',
    failureReason: 'OTP expired — requested new OTP',
    location: 'Manchester, UK',
  },
  {
    id: 'LOG-014',
    userName: 'Priya Patel',
    email: 'priya.patel@hss.org.uk',
    role: 'Admin',
    loginTime: '2026-05-26T08:38:00Z',
    logoutTime: '2026-05-26T17:00:00Z',
    ipAddress: '81.107.44.78',
    device: 'MacBook Air',
    browser: 'Safari 17.4',
    os: 'macOS 14.3',
    status: 'Success',
    location: 'Manchester, UK',
    sessionDuration: '8h 22m',
  },
  {
    id: 'LOG-015',
    userName: 'Michael Kumar',
    email: 'michael.kumar@hss.org.uk',
    role: 'Editor',
    loginTime: '2026-05-25T09:40:00Z',
    logoutTime: '2026-05-25T13:00:00Z',
    ipAddress: '86.156.78.90',
    device: 'Dell XPS 15',
    browser: 'Firefox 125.0',
    os: 'Windows 11',
    status: 'Success',
    location: 'Leeds, UK',
    sessionDuration: '3h 20m',
  },
  {
    id: 'LOG-016',
    userName: 'Rahul Gupta',
    email: 'rahul.gupta@hss.org.uk',
    role: 'Admin',
    loginTime: '2026-05-22T10:25:00Z',
    logoutTime: '2026-05-22T16:50:00Z',
    ipAddress: '217.155.32.48',
    device: 'Samsung Galaxy S24',
    browser: 'Chrome Mobile 124.0',
    os: 'Android 14',
    status: 'Success',
    location: 'Glasgow, UK',
    sessionDuration: '6h 25m',
  },
  {
    id: 'LOG-017',
    userName: 'Unknown',
    email: 'john.doe@hss.org.uk',
    role: 'None',
    loginTime: '2026-05-21T04:12:00Z',
    logoutTime: null,
    ipAddress: '91.108.56.130',
    device: 'Unknown Device',
    browser: 'Unknown',
    os: 'Unknown',
    status: 'Failed',
    failureReason: 'Invalid password',
    location: 'Unknown — Proxy detected',
  },
  {
    id: 'LOG-018',
    userName: 'Sunita Sharma',
    email: 'sunita.sharma@hss.org.uk',
    role: 'Editor',
    loginTime: '2026-05-21T13:55:00Z',
    logoutTime: '2026-05-21T17:30:00Z',
    ipAddress: '81.109.23.55',
    device: 'iPad Pro',
    browser: 'Safari Mobile 17.4',
    os: 'iPadOS 17.4',
    status: 'Success',
    location: 'Leicester, UK',
    sessionDuration: '3h 35m',
  },
  {
    id: 'LOG-019',
    userName: 'John Doe',
    email: 'john.doe@hss.org.uk',
    role: 'Super Admin',
    loginTime: '2026-05-20T07:58:00Z',
    logoutTime: '2026-05-20T19:15:00Z',
    ipAddress: '82.132.201.14',
    device: 'MacBook Pro 14"',
    browser: 'Chrome 124.0',
    os: 'macOS 14.4',
    status: 'Success',
    location: 'London, UK',
    sessionDuration: '11h 17m',
  },
  {
    id: 'LOG-020',
    userName: 'Sarah Smith',
    email: 'sarah.smith@hss.org.uk',
    role: 'Admin',
    loginTime: '2026-05-15T09:28:00Z',
    logoutTime: '2026-05-15T17:00:00Z',
    ipAddress: '86.143.56.22',
    device: 'Windows PC',
    browser: 'Edge 124.0',
    os: 'Windows 11',
    status: 'Success',
    location: 'Birmingham, UK',
    sessionDuration: '7h 32m',
  },
];

// ── Audit Logs ────────────────────────────────────────────────
// 35 entries — all write/mutate actions across every HSS module
// No view actions. No login actions (those live in Login Logs).
export const mockAuditLogs: AuditLog[] = [
  {
    id: 'AUD-001',
    user: 'John Doe',
    module: 'Members',
    actionType: 'Create',
    recordName: 'Arjun Sharma',
    recordId: 'MBR-210',
    description: 'New member registered: Arjun Sharma (Tarun, Karyawaha) — Leeds North Activity Centre.',
    timestamp: '2026-05-30T08:45:00Z',
    ipAddress: '82.132.201.14',
    details: {
      after: { name: 'Arjun Sharma', ageGroup: 'tarun', role: 'Karyawaha', centre: 'Leeds North Activity Centre', status: 'active' },
      changedFields: ['name', 'ageGroup', 'role', 'centre', 'status'],
    },
  },
  {
    id: 'AUD-002',
    user: 'Sarah Smith',
    module: 'Members',
    actionType: 'Export',
    recordName: 'All Members — Full Export',
    recordId: 'EXPORT-20260530',
    description: 'Exported full member list (210 records) as CSV. Includes personal details, region, and compliance status.',
    timestamp: '2026-05-30T09:22:00Z',
    ipAddress: '86.143.56.22',
    details: {
      after: { format: 'CSV', recordCount: 210, fields: ['name', 'email', 'region', 'status', 'compliance'] },
    },
  },
  {
    id: 'AUD-003',
    user: 'Priya Patel',
    module: 'Karyakrams',
    actionType: 'Create',
    recordName: 'HSS Annual General Meeting 2026',
    recordId: 'EVT-006',
    description: 'Created new event: HSS Annual General Meeting 2026 at Harrow Activity Centre on 24 May 2026.',
    timestamp: '2026-05-29T10:30:00Z',
    ipAddress: '81.107.44.78',
    details: {
      after: { title: 'HSS Annual General Meeting 2026', venue: 'Harrow Activity Centre', date: '2026-05-24', status: 'active', capacity: 400 },
      changedFields: ['title', 'venue', 'date', 'status', 'capacity'],
    },
  },
  {
    id: 'AUD-004',
    user: 'John Doe',
    module: 'Sessions',
    actionType: 'Create',
    recordName: 'Leeds Shakha — Fortnightly Milan',
    recordId: 'SES-015',
    description: 'Created new Shakha session: Leeds Shakha — Fortnightly Milan at Leeds North Activity Centre, 23 May 2026, 14:00–16:00.',
    timestamp: '2026-05-29T11:05:00Z',
    ipAddress: '82.132.201.14',
    details: {
      after: { title: 'Leeds Shakha — Fortnightly Milan', centre: 'Leeds North Activity Centre', date: '2026-05-23', startTime: '14:00', endTime: '16:00', shakhaType: 'Milan' },
      changedFields: ['title', 'centre', 'date', 'startTime', 'endTime', 'shakhaType'],
    },
  },
  {
    id: 'AUD-005',
    user: 'Michael Kumar',
    module: 'Members',
    actionType: 'Update',
    recordName: 'Nisha Kapoor',
    recordId: 'MBR-022',
    description: 'Updated profile for Nisha Kapoor: phone number and emergency contact details changed.',
    timestamp: '2026-05-29T14:33:00Z',
    ipAddress: '86.156.78.90',
    details: {
      before: { phone: '+44 7700 900123', emergencyContactName: 'Raj Kapoor' },
      after: { phone: '+44 7700 900456', emergencyContactName: 'Sunita Kapoor' },
      changedFields: ['phone', 'emergencyContactName'],
    },
  },
  {
    id: 'AUD-006',
    user: 'Rahul Gupta',
    module: 'Attendance',
    actionType: 'Export',
    recordName: 'Attendance Log — May 2026',
    recordId: 'EXPORT-ATT-20260529',
    description: 'Exported attendance log for May 2026 (255 records) as CSV. Filtered by all centres.',
    timestamp: '2026-05-29T16:02:00Z',
    ipAddress: '217.155.32.48',
    details: {
      after: { format: 'CSV', recordCount: 255, month: 'May 2026', centres: 'All' },
    },
  },
  {
    id: 'AUD-007',
    user: 'Sarah Smith',
    module: 'Members',
    actionType: 'Status Change',
    recordName: 'Deepak Sharma',
    recordId: 'MBR-031',
    description: 'Member status changed from Active to Inactive for Deepak Sharma (Tarun, Karyawaha).',
    timestamp: '2026-05-28T09:18:00Z',
    ipAddress: '86.143.56.22',
    details: {
      before: { status: 'active' },
      after: { status: 'inactive' },
      changedFields: ['status'],
    },
  },
  {
    id: 'AUD-008',
    user: 'John Doe',
    module: 'Role Management',
    actionType: 'Permission Update',
    recordName: 'Editor Role',
    recordId: 'ROLE-003',
    description: 'Editor role permissions updated: Attendance module access granted (View + Export).',
    timestamp: '2026-05-28T10:05:00Z',
    ipAddress: '82.132.201.14',
    details: {
      before: { permissions: ['members.view', 'events.view'] },
      after: { permissions: ['members.view', 'events.view', 'attendance.view', 'attendance.export'] },
      changedFields: ['permissions'],
    },
  },
  {
    id: 'AUD-009',
    user: 'Priya Patel',
    module: 'Suchana',
    actionType: 'Create',
    recordName: 'HSS Annual Camp 2026',
    recordId: 'ANN-012',
    description: 'Published new announcement: HSS Annual Camp 2026 registration now open. Sent to all active members.',
    timestamp: '2026-05-28T11:32:00Z',
    ipAddress: '81.107.44.78',
    details: {
      after: { title: 'HSS Annual Camp 2026', priority: 'High', audience: 'All Active Members', status: 'published' },
      changedFields: ['title', 'priority', 'audience', 'status'],
    },
  },
  {
    id: 'AUD-010',
    user: 'Michael Kumar',
    module: 'Karyakrams',
    actionType: 'Update',
    recordName: 'Youth Leadership Summit',
    recordId: 'EVT-001',
    description: 'Event updated: Youth Leadership Summit — venue changed from Birmingham Central to Wembley Activity Centre.',
    timestamp: '2026-05-27T09:05:00Z',
    ipAddress: '86.156.78.90',
    details: {
      before: { venue: 'Birmingham Central Activity Centre' },
      after: { venue: 'Wembley Activity Centre' },
      changedFields: ['venue'],
    },
  },
  {
    id: 'AUD-011',
    user: 'Sarah Smith',
    module: 'Members',
    actionType: 'Import',
    recordName: 'Bulk Member Import — Yorkshire Region',
    recordId: 'IMPORT-20260527',
    description: 'Imported 15 new members for Yorkshire & Humber region from CSV. 14 successful, 1 skipped (duplicate email).',
    timestamp: '2026-05-27T10:34:00Z',
    ipAddress: '86.143.56.22',
    details: {
      after: { totalRows: 15, imported: 14, skipped: 1, skipReason: 'Duplicate email', region: 'Yorkshire & Humber' },
    },
  },
  {
    id: 'AUD-012',
    user: 'John Doe',
    module: 'Settings',
    actionType: 'Update',
    recordName: 'System Email Settings',
    recordId: 'SETTINGS-EMAIL',
    description: 'System email configuration updated: SMTP host changed and reply-to address updated to noreply@hss.org.uk.',
    timestamp: '2026-05-27T14:05:00Z',
    ipAddress: '82.132.201.14',
    details: {
      before: { smtpHost: 'smtp.oldprovider.com', replyTo: 'admin@hss.org.uk' },
      after: { smtpHost: 'smtp.sendgrid.net', replyTo: 'noreply@hss.org.uk' },
      changedFields: ['smtpHost', 'replyTo'],
    },
  },
  {
    id: 'AUD-013',
    user: 'Rahul Gupta',
    module: 'Sessions',
    actionType: 'Create',
    recordName: 'Manchester Shakha — Sewa Shakha',
    recordId: 'SES-014',
    description: 'Created new Shakha session: Manchester Shakha — Sewa Shakha at Manchester Central Activity Centre, 21 May 2026, 19:00–21:00.',
    timestamp: '2026-05-26T09:33:00Z',
    ipAddress: '217.155.32.48',
    details: {
      after: { title: 'Manchester Shakha — Sewa Shakha', centre: 'Manchester Central Activity Centre', date: '2026-05-21', startTime: '19:00', endTime: '21:00', shakhaType: 'Sewa Shakha' },
      changedFields: ['title', 'centre', 'date', 'startTime', 'endTime', 'shakhaType'],
    },
  },
  {
    id: 'AUD-014',
    user: 'Priya Patel',
    module: 'Attendance',
    actionType: 'Create',
    recordName: 'Attendance — Leeds Session (23 May 2026)',
    recordId: 'ATT-BATCH-SES012',
    description: 'Attendance marked for 18 members in Leeds Shakha — Fortnightly Milan session (23 May 2026). 12 present, 6 absent.',
    timestamp: '2026-05-26T11:02:00Z',
    ipAddress: '81.107.44.78',
    details: {
      after: { sessionId: 'SES-012', sessionDate: '2026-05-23', totalMarked: 18, present: 12, absent: 6 },
    },
  },
  {
    id: 'AUD-015',
    user: 'Sarah Smith',
    module: 'Karyakrams',
    actionType: 'Delete',
    recordName: 'Birmingham Fundraiser — May 2026',
    recordId: 'EVT-004',
    description: 'Event deleted: Birmingham Fundraiser — May 2026. Reason: Cancelled due to venue unavailability.',
    timestamp: '2026-05-26T13:35:00Z',
    ipAddress: '86.143.56.22',
    details: {
      before: { title: 'Birmingham Fundraiser — May 2026', status: 'active', registrations: 42 },
      after: null,
      changedFields: ['deleted'],
    },
  },
  {
    id: 'AUD-016',
    user: 'John Doe',
    module: 'Email Templates',
    actionType: 'Update',
    recordName: 'Welcome Email',
    recordId: 'TMPL-001',
    description: 'Welcome Email template updated: subject line and body content revised to reflect 2026 branding.',
    timestamp: '2026-05-25T09:05:00Z',
    ipAddress: '82.132.201.14',
    details: {
      before: { subject: 'Welcome to HSS UK!', lastUpdated: '2024-01-10' },
      after: { subject: 'Welcome to Hindu Swayamsevak Sangh UK 🙏', lastUpdated: '2026-05-25' },
      changedFields: ['subject', 'body', 'lastUpdated'],
    },
  },
  {
    id: 'AUD-017',
    user: 'Michael Kumar',
    module: 'Members',
    actionType: 'Status Change',
    recordName: 'Sonia Shah',
    recordId: 'MBR-045',
    description: 'Member status changed from Pending to Active for Sonia Shah after guardian consent was received.',
    timestamp: '2026-05-25T10:18:00Z',
    ipAddress: '86.156.78.90',
    details: {
      before: { status: 'pending-parental-consent' },
      after: { status: 'active' },
      changedFields: ['status'],
    },
  },
  {
    id: 'AUD-018',
    user: 'Sunita Sharma',
    module: 'Suchana',
    actionType: 'Update',
    recordName: 'General Meeting — June 2026',
    recordId: 'ANN-011',
    description: 'Announcement updated: General Meeting — June 2026 — date corrected from 10 Jun to 12 Jun 2026.',
    timestamp: '2026-05-25T13:04:00Z',
    ipAddress: '81.109.23.55',
    details: {
      before: { date: '2026-06-10' },
      after: { date: '2026-06-12' },
      changedFields: ['date', 'body'],
    },
  },
  {
    id: 'AUD-019',
    user: 'Priya Patel',
    module: 'Members',
    actionType: 'Export',
    recordName: 'North West Region — Member Report',
    recordId: 'EXPORT-NW-20260524',
    description: 'Exported North West region member report (28 records) as CSV for regional coordinator review.',
    timestamp: '2026-05-24T09:32:00Z',
    ipAddress: '81.107.44.78',
    details: {
      after: { format: 'CSV', recordCount: 28, region: 'North West', fields: ['name', 'role', 'centre', 'status'] },
    },
  },
  {
    id: 'AUD-020',
    user: 'Rahul Gupta',
    module: 'Sessions',
    actionType: 'Update',
    recordName: 'Glasgow Shakha — Fortnightly',
    recordId: 'SES-010',
    description: 'Session time updated: Glasgow Shakha — Fortnightly rescheduled from 18:00–20:00 to 19:00–21:00.',
    timestamp: '2026-05-24T11:08:00Z',
    ipAddress: '217.155.32.48',
    details: {
      before: { startTime: '18:00', endTime: '20:00' },
      after: { startTime: '19:00', endTime: '21:00' },
      changedFields: ['startTime', 'endTime'],
    },
  },
  {
    id: 'AUD-021',
    user: 'John Doe',
    module: 'Role Management',
    actionType: 'Permission Update',
    recordName: 'Admin Role',
    recordId: 'ROLE-002',
    description: 'Admin role permissions updated: "Delete Members" permission removed for data protection compliance.',
    timestamp: '2026-05-24T14:00:00Z',
    ipAddress: '82.132.201.14',
    details: {
      before: { permissions: ['members.view', 'members.edit', 'members.delete', 'events.manage'] },
      after: { permissions: ['members.view', 'members.edit', 'events.manage'] },
      changedFields: ['permissions'],
    },
  },
  {
    id: 'AUD-022',
    user: 'Sarah Smith',
    module: 'Karyakrams',
    actionType: 'Status Change',
    recordName: 'Cultural Evening — Edinburgh',
    recordId: 'EVT-005',
    description: 'Event status changed from Draft to Published for Cultural Evening — Edinburgh (11 Jun 2026).',
    timestamp: '2026-05-23T09:02:00Z',
    ipAddress: '86.143.56.22',
    details: {
      before: { status: 'draft' },
      after: { status: 'published' },
      changedFields: ['status'],
    },
  },
  {
    id: 'AUD-023',
    user: 'Michael Kumar',
    module: 'Members',
    actionType: 'Create',
    recordName: 'Vikram Singh',
    recordId: 'MBR-209',
    description: 'New member registered: Vikram Singh (Tarun, Ghatnayak) — Manchester Central Activity Centre.',
    timestamp: '2026-05-23T10:35:00Z',
    ipAddress: '86.156.78.90',
    details: {
      after: { name: 'Vikram Singh', ageGroup: 'tarun', role: 'Ghatnayak', centre: 'Manchester Central Activity Centre', status: 'active' },
      changedFields: ['name', 'ageGroup', 'role', 'centre', 'status'],
    },
  },
  {
    id: 'AUD-024',
    user: 'Priya Patel',
    module: 'Attendance',
    actionType: 'Export',
    recordName: 'Attendance Report — Manchester Central',
    recordId: 'EXPORT-ATT-MCR-20260522',
    description: 'Exported attendance report for Manchester Central Activity Centre (April–May 2026, 68 records).',
    timestamp: '2026-05-22T11:05:00Z',
    ipAddress: '81.107.44.78',
    details: {
      after: { format: 'CSV', recordCount: 68, centre: 'Manchester Central Activity Centre', period: 'April–May 2026' },
    },
  },
  {
    id: 'AUD-025',
    user: 'John Doe',
    module: 'Static Pages',
    actionType: 'Update',
    recordName: 'Terms & Conditions',
    recordId: 'SP-001',
    description: 'Terms & Conditions page content updated to reflect updated GDPR data retention policy (Section 3).',
    timestamp: '2026-05-22T13:10:00Z',
    ipAddress: '82.132.201.14',
    details: {
      before: { lastUpdated: '2024-03-15', updatedBy: 'Admin Sarah' },
      after: { lastUpdated: '2026-05-22', updatedBy: 'John Doe' },
      changedFields: ['content', 'lastUpdated', 'updatedBy'],
    },
  },
  {
    id: 'AUD-026',
    user: 'Rahul Gupta',
    module: 'Members',
    actionType: 'Delete',
    recordName: 'MBR-089 (Inactive)',
    recordId: 'MBR-089',
    description: 'Permanently deleted inactive member record MBR-089. Member had no activity for over 24 months.',
    timestamp: '2026-05-21T09:05:00Z',
    ipAddress: '217.155.32.48',
    details: {
      before: { status: 'inactive', lastActivity: '2024-01-10', name: '[Redacted]' },
      after: null,
      changedFields: ['deleted'],
    },
  },
  {
    id: 'AUD-027',
    user: 'Sunita Sharma',
    module: 'Suchana',
    actionType: 'Delete',
    recordName: 'Diwali Celebration 2024',
    recordId: 'ANN-003',
    description: 'Outdated announcement removed: Diwali Celebration 2024 (posted Oct 2024, past event).',
    timestamp: '2026-05-21T11:38:00Z',
    ipAddress: '81.109.23.55',
    details: {
      before: { title: 'Diwali Celebration 2024', status: 'published', date: '2024-10-31' },
      after: null,
      changedFields: ['deleted'],
    },
  },
  {
    id: 'AUD-028',
    user: 'Sarah Smith',
    module: 'Sessions',
    actionType: 'Create',
    recordName: 'Birmingham Shakha — Fortnightly',
    recordId: 'SES-013',
    description: 'Created new Shakha session: Birmingham Shakha — Fortnightly at Birmingham East Activity Centre, 20 May 2026, 18:30–20:30.',
    timestamp: '2026-05-20T10:08:00Z',
    ipAddress: '86.143.56.22',
    details: {
      after: { title: 'Birmingham Shakha — Fortnightly', centre: 'Birmingham East Activity Centre', date: '2026-05-20', startTime: '18:30', endTime: '20:30' },
      changedFields: ['title', 'centre', 'date', 'startTime', 'endTime'],
    },
  },
  {
    id: 'AUD-029',
    user: 'Priya Patel',
    module: 'Karyakrams',
    actionType: 'Create',
    recordName: 'Fundraising Gala — Dublin',
    recordId: 'EVT-003',
    description: 'Created new event: Fundraising Gala at Dublin Activity Centre, 23 May 2026. Ticket price set to £75.',
    timestamp: '2026-05-19T09:35:00Z',
    ipAddress: '81.107.44.78',
    details: {
      after: { title: 'Fundraising Gala', venue: 'Dublin Activity Centre', date: '2026-05-23', ticketPrice: 75, status: 'active' },
      changedFields: ['title', 'venue', 'date', 'ticketPrice', 'status'],
    },
  },
  {
    id: 'AUD-030',
    user: 'John Doe',
    module: 'Members',
    actionType: 'Import',
    recordName: 'Bulk Import — Online Registration Form',
    recordId: 'IMPORT-20260518',
    description: 'Imported 8 new members from online registration form submissions. All 8 records successfully imported.',
    timestamp: '2026-05-18T14:03:00Z',
    ipAddress: '82.132.201.14',
    details: {
      after: { totalRows: 8, imported: 8, skipped: 0, source: 'Online Registration Form' },
    },
  },
  {
    id: 'AUD-031',
    user: 'Michael Kumar',
    module: 'Email Templates',
    actionType: 'Update',
    recordName: 'Session Reminder',
    recordId: 'TMPL-005',
    description: 'Session Reminder email template updated: added Shakha location map link and updated footer.',
    timestamp: '2026-05-17T10:08:00Z',
    ipAddress: '86.156.78.90',
    details: {
      before: { lastUpdated: '2025-11-20' },
      after: { lastUpdated: '2026-05-17' },
      changedFields: ['body', 'lastUpdated'],
    },
  },
  {
    id: 'AUD-032',
    user: 'Sarah Smith',
    module: 'Members',
    actionType: 'Update',
    recordName: 'Amit Rao',
    recordId: 'MBR-057',
    description: 'Profile updated for Amit Rao: emergency contact details and dietary requirements updated.',
    timestamp: '2026-05-16T09:18:00Z',
    ipAddress: '86.143.56.22',
    details: {
      before: { emergencyContactName: 'Ravi Rao', dietaryRequirements: [] },
      after: { emergencyContactName: 'Sunita Rao', dietaryRequirements: ['Gluten-free'] },
      changedFields: ['emergencyContactName', 'emergencyContactPhone', 'dietaryRequirements'],
    },
  },
  {
    id: 'AUD-033',
    user: 'Rahul Gupta',
    module: 'Settings',
    actionType: 'Update',
    recordName: 'Notification Settings',
    recordId: 'SETTINGS-NOTIF',
    description: 'System notification settings updated: session reminder lead time changed from 24h to 48h.',
    timestamp: '2026-05-15T11:05:00Z',
    ipAddress: '217.155.32.48',
    details: {
      before: { sessionReminderHours: 24 },
      after: { sessionReminderHours: 48 },
      changedFields: ['sessionReminderHours'],
    },
  },
  {
    id: 'AUD-034',
    user: 'John Doe',
    module: 'Role Management',
    actionType: 'Create',
    recordName: 'Regional Coordinator',
    recordId: 'ROLE-006',
    description: 'New role created: Regional Coordinator with access to view members, sessions, and attendance for assigned region.',
    timestamp: '2026-05-14T09:02:00Z',
    ipAddress: '82.132.201.14',
    details: {
      after: { roleName: 'Regional Coordinator', permissions: ['members.view', 'sessions.view', 'attendance.view'], scope: 'Regional' },
      changedFields: ['roleName', 'permissions', 'scope'],
    },
  },
  {
    id: 'AUD-035',
    user: 'Priya Patel',
    module: 'Members',
    actionType: 'Status Change',
    recordName: 'Meera Iyer',
    recordId: 'MBR-078',
    description: 'Member status changed from Inactive to Active for Meera Iyer following re-registration.',
    timestamp: '2026-05-13T10:35:00Z',
    ipAddress: '81.107.44.78',
    details: {
      before: { status: 'inactive' },
      after: { status: 'active' },
      changedFields: ['status'],
    },
  },
];

// ── API Logs ──────────────────────────────────────────────────
// 20 entries — HSS mobile app API calls
export const mockAPILogs: APILog[] = [
  {
    id: 'API-001',
    apiName: 'Member Login',
    endpoint: '/api/v1/auth/login',
    method: 'POST',
    status: 200,
    requestTime: '2026-05-30T08:31:00Z',
    responseTime: '124',
    user: 'Arjun Sharma',
    requestPayload: '{"email":"arjun.sharma@gmail.com","password":"••••••••"}',
    responsePayload: '{"token":"eyJhbGciOiJIUzI1NiJ9...","expiresIn":3600,"member":{"id":"MBR-001","name":"Arjun Sharma"}}',
    headers: { 'Content-Type': 'application/json', 'X-App-Version': '2.4.1', 'X-Device-OS': 'iOS 17.4' },
  },
  {
    id: 'API-002',
    apiName: 'Get Upcoming Sessions',
    endpoint: '/api/v1/sessions',
    method: 'GET',
    status: 200,
    requestTime: '2026-05-30T08:32:00Z',
    responseTime: '89',
    user: 'Arjun Sharma',
    requestPayload: '{"centreId":"ACT-LEEDS-NORTH","upcoming":true}',
    responsePayload: '{"data":[{"id":"SES-015","title":"Leeds Shakha — Fortnightly Milan","date":"2026-05-30"}],"total":3}',
    headers: { 'Content-Type': 'application/json', 'Authorization': 'Bearer eyJhbGci...', 'X-App-Version': '2.4.1' },
  },
  {
    id: 'API-003',
    apiName: 'Mark Attendance — Check In',
    endpoint: '/api/v1/sessions/SES-015/attend',
    method: 'POST',
    status: 201,
    requestTime: '2026-05-30T08:45:00Z',
    responseTime: '210',
    user: 'Arjun Sharma',
    requestPayload: '{"memberId":"MBR-001","sessionId":"SES-015","status":"present","markedAt":"2026-05-30T08:44:55Z"}',
    responsePayload: '{"attendanceId":"ATT-1892","status":"present","message":"Attendance marked successfully"}',
    headers: { 'Content-Type': 'application/json', 'Authorization': 'Bearer eyJhbGci...', 'X-App-Version': '2.4.1' },
  },
  {
    id: 'API-004',
    apiName: 'Get Upcoming Events',
    endpoint: '/api/v1/events',
    method: 'GET',
    status: 200,
    requestTime: '2026-05-29T09:15:00Z',
    responseTime: '145',
    user: 'Nisha Kapoor',
    requestPayload: '{"status":"active","upcoming":true,"limit":10}',
    responsePayload: '{"data":[{"id":"EVT-001","title":"Youth Leadership Summit"},{"id":"EVT-006","title":"HSS Annual General Meeting 2026"}],"total":5}',
    headers: { 'Content-Type': 'application/json', 'Authorization': 'Bearer eyJhbGci...', 'X-App-Version': '2.4.0' },
  },
  {
    id: 'API-005',
    apiName: 'Update Member Profile',
    endpoint: '/api/v1/members/MBR-031/profile',
    method: 'PUT',
    status: 200,
    requestTime: '2026-05-29T10:30:00Z',
    responseTime: '320',
    user: 'Deepak Sharma',
    requestPayload: '{"phone":"+44 7911 123456","emergencyContactName":"Raj Sharma","emergencyContactPhone":"+44 7800 654321"}',
    responsePayload: '{"success":true,"message":"Profile updated","updatedAt":"2026-05-29T10:30:18Z"}',
    headers: { 'Content-Type': 'application/json', 'Authorization': 'Bearer eyJhbGci...', 'X-App-Version': '2.4.1' },
  },
  {
    id: 'API-006',
    apiName: 'Refresh Auth Token',
    endpoint: '/api/v1/auth/refresh',
    method: 'POST',
    status: 401,
    requestTime: '2026-05-29T14:00:00Z',
    responseTime: '45',
    user: 'Meera Iyer',
    requestPayload: '{"refreshToken":"dGhpcyBpcyBhIHRlc3Q..."}',
    responsePayload: '{"error":"Unauthorized","message":"Refresh token expired. Please log in again.","code":"TOKEN_EXPIRED"}',
    headers: { 'Content-Type': 'application/json', 'X-App-Version': '2.3.8' },
  },
  {
    id: 'API-007',
    apiName: 'Get Announcements',
    endpoint: '/api/v1/announcements',
    method: 'GET',
    status: 200,
    requestTime: '2026-05-29T09:02:00Z',
    responseTime: '98',
    user: 'Vikram Singh',
    requestPayload: '{"status":"published","limit":20}',
    responsePayload: '{"data":[{"id":"ANN-012","title":"HSS Annual Camp 2026"},{"id":"ANN-011","title":"General Meeting — June 2026"}],"total":5}',
    headers: { 'Content-Type': 'application/json', 'Authorization': 'Bearer eyJhbGci...', 'X-App-Version': '2.4.1' },
  },
  {
    id: 'API-008',
    apiName: 'Get Member Profile',
    endpoint: '/api/v1/members/MBR-045/profile',
    method: 'GET',
    status: 200,
    requestTime: '2026-05-28T11:30:00Z',
    responseTime: '112',
    user: 'Sonia Shah',
    requestPayload: '{}',
    responsePayload: '{"id":"MBR-045","name":"Sonia Shah","role":"Sewa","centre":"Manchester Central Activity Centre","status":"active"}',
    headers: { 'Content-Type': 'application/json', 'Authorization': 'Bearer eyJhbGci...', 'X-App-Version': '2.4.1' },
  },
  {
    id: 'API-009',
    apiName: 'Mark Attendance — Check In',
    endpoint: '/api/v1/sessions/SES-014/attend',
    method: 'POST',
    status: 201,
    requestTime: '2026-05-28T14:02:00Z',
    responseTime: '187',
    user: 'Amit Rao',
    requestPayload: '{"memberId":"MBR-057","sessionId":"SES-014","status":"present","markedAt":"2026-05-28T14:01:50Z"}',
    responsePayload: '{"attendanceId":"ATT-1891","status":"present","message":"Attendance marked successfully"}',
    headers: { 'Content-Type': 'application/json', 'Authorization': 'Bearer eyJhbGci...', 'X-App-Version': '2.4.1' },
  },
  {
    id: 'API-010',
    apiName: 'Get Session Detail',
    endpoint: '/api/v1/sessions/SES-010',
    method: 'GET',
    status: 200,
    requestTime: '2026-05-27T08:30:00Z',
    responseTime: '76',
    user: 'Arjun Sharma',
    requestPayload: '{}',
    responsePayload: '{"id":"SES-010","title":"Glasgow Shakha — Fortnightly","date":"2026-05-14","startTime":"19:00","endTime":"21:00","attendeeCount":12}',
    headers: { 'Content-Type': 'application/json', 'Authorization': 'Bearer eyJhbGci...', 'X-App-Version': '2.4.1' },
  },
  {
    id: 'API-011',
    apiName: 'Member Login',
    endpoint: '/api/v1/auth/login',
    method: 'POST',
    status: 200,
    requestTime: '2026-05-27T09:10:00Z',
    responseTime: '134',
    user: 'Nisha Kapoor',
    requestPayload: '{"email":"nisha.kapoor@gmail.com","password":"••••••••"}',
    responsePayload: '{"token":"eyJhbGciOiJIUzI1NiJ9...","expiresIn":3600,"member":{"id":"MBR-022","name":"Nisha Kapoor"}}',
    headers: { 'Content-Type': 'application/json', 'X-App-Version': '2.4.0', 'X-Device-OS': 'Android 14' },
  },
  {
    id: 'API-012',
    apiName: 'Get Event Detail',
    endpoint: '/api/v1/events/EVT-099',
    method: 'GET',
    status: 404,
    requestTime: '2026-05-27T11:00:00Z',
    responseTime: '23',
    user: 'Deepak Sharma',
    requestPayload: '{}',
    responsePayload: '{"error":"Not Found","message":"Event EVT-099 does not exist or has been removed.","code":"RESOURCE_NOT_FOUND"}',
    headers: { 'Content-Type': 'application/json', 'Authorization': 'Bearer eyJhbGci...', 'X-App-Version': '2.4.1' },
  },
  {
    id: 'API-013',
    apiName: 'Get Member Profile',
    endpoint: '/api/v1/members/MBR-078/profile',
    method: 'GET',
    status: 500,
    requestTime: '2026-05-26T08:00:00Z',
    responseTime: '5021',
    user: 'Suresh Pillai',
    requestPayload: '{}',
    responsePayload: '{"error":"Internal Server Error","message":"Database connection timeout. Please retry.","code":"DB_TIMEOUT","requestId":"req_9a8f2c"}',
    headers: { 'Content-Type': 'application/json', 'Authorization': 'Bearer eyJhbGci...', 'X-App-Version': '2.3.9' },
  },
  {
    id: 'API-014',
    apiName: 'Mark Attendance — Check In',
    endpoint: '/api/v1/sessions/SES-009/attend',
    method: 'POST',
    status: 201,
    requestTime: '2026-05-26T09:32:00Z',
    responseTime: '195',
    user: 'Meera Iyer',
    requestPayload: '{"memberId":"MBR-078","sessionId":"SES-009","status":"present","markedAt":"2026-05-26T09:31:45Z"}',
    responsePayload: '{"attendanceId":"ATT-1890","status":"present","message":"Attendance marked successfully"}',
    headers: { 'Content-Type': 'application/json', 'Authorization': 'Bearer eyJhbGci...', 'X-App-Version': '2.4.1' },
  },
  {
    id: 'API-015',
    apiName: 'Get Announcements',
    endpoint: '/api/v1/announcements',
    method: 'GET',
    status: 200,
    requestTime: '2026-05-25T10:02:00Z',
    responseTime: '88',
    user: 'Anita Desai',
    requestPayload: '{"status":"published","limit":10}',
    responsePayload: '{"data":[{"id":"ANN-012","title":"HSS Annual Camp 2026"}],"total":5}',
    headers: { 'Content-Type': 'application/json', 'Authorization': 'Bearer eyJhbGci...', 'X-App-Version': '2.4.1' },
  },
  {
    id: 'API-016',
    apiName: 'Update Member Profile',
    endpoint: '/api/v1/members/MBR-209/profile',
    method: 'PUT',
    status: 400,
    requestTime: '2026-05-25T14:33:00Z',
    responseTime: '56',
    user: 'Vikram Singh',
    requestPayload: '{"phone":"invalid-number","postCode":"ABCDEF"}',
    responsePayload: '{"error":"Validation Failed","message":"Invalid phone number format. Invalid postcode format.","fields":{"phone":"Must be a valid UK number","postCode":"Must be a valid UK postcode"}}',
    headers: { 'Content-Type': 'application/json', 'Authorization': 'Bearer eyJhbGci...', 'X-App-Version': '2.4.1' },
  },
  {
    id: 'API-017',
    apiName: 'Member Login',
    endpoint: '/api/v1/auth/login',
    method: 'POST',
    status: 200,
    requestTime: '2026-05-24T09:01:00Z',
    responseTime: '118',
    user: 'Sonia Shah',
    requestPayload: '{"email":"sonia.shah@gmail.com","password":"••••••••"}',
    responsePayload: '{"token":"eyJhbGciOiJIUzI1NiJ9...","expiresIn":3600,"member":{"id":"MBR-045","name":"Sonia Shah"}}',
    headers: { 'Content-Type': 'application/json', 'X-App-Version': '2.4.1', 'X-Device-OS': 'iOS 17.4' },
  },
  {
    id: 'API-018',
    apiName: 'Get Member Attendance History',
    endpoint: '/api/v1/members/MBR-001/attendance',
    method: 'GET',
    status: 200,
    requestTime: '2026-05-24T10:32:00Z',
    responseTime: '234',
    user: 'Arjun Sharma',
    requestPayload: '{"from":"2026-01-01","to":"2026-05-24","limit":50}',
    responsePayload: '{"data":[{"sessionId":"SES-014","date":"2026-05-21","status":"present"},{"sessionId":"SES-012","date":"2026-05-23","status":"present"}],"total":18,"attendanceRate":"78%"}',
    headers: { 'Content-Type': 'application/json', 'Authorization': 'Bearer eyJhbGci...', 'X-App-Version': '2.4.1' },
  },
  {
    id: 'API-019',
    apiName: 'Mark Attendance — Check In',
    endpoint: '/api/v1/sessions/SES-012/attend',
    method: 'POST',
    status: 201,
    requestTime: '2026-05-23T14:02:00Z',
    responseTime: '178',
    user: 'Suresh Pillai',
    requestPayload: '{"memberId":"MBR-011","sessionId":"SES-012","status":"present","markedAt":"2026-05-23T14:01:30Z"}',
    responsePayload: '{"attendanceId":"ATT-1885","status":"present","message":"Attendance marked successfully"}',
    headers: { 'Content-Type': 'application/json', 'Authorization': 'Bearer eyJhbGci...', 'X-App-Version': '2.4.0' },
  },
  {
    id: 'API-020',
    apiName: 'Get Upcoming Events',
    endpoint: '/api/v1/events',
    method: 'GET',
    status: 200,
    requestTime: '2026-05-23T09:32:00Z',
    responseTime: '142',
    user: 'Anita Desai',
    requestPayload: '{"status":"active","upcoming":true,"limit":10}',
    responsePayload: '{"data":[{"id":"EVT-001","title":"Youth Leadership Summit"},{"id":"EVT-003","title":"Fundraising Gala — Dublin"}],"total":5}',
    headers: { 'Content-Type': 'application/json', 'Authorization': 'Bearer eyJhbGci...', 'X-App-Version': '2.4.1' },
  },
];

// ── Email Logs ────────────────────────────────────────────────
// 15 entries — system-triggered emails for HSS workflows
export const mockEmailLogs: EmailLog[] = [
  {
    id: 'EML-001',
    recipientName: 'Arjun Sharma',
    recipientEmail: 'arjun.sharma@gmail.com',
    templateName: 'Member Registration Confirmation',
    subject: 'Welcome — Your HSS UK membership registration is confirmed',
    sentAt: '2026-05-30T08:46:00Z',
    status: 'Delivered',
    triggeredBy: 'System — Member Registration (MBR-210)',
    contentPreview: 'Dear Arjun, your HSS UK membership registration has been received and confirmed. Your member ID is MBR-210. You are registered at Leeds North Activity Centre...',
  },
  {
    id: 'EML-002',
    recipientName: 'Sarah Smith',
    recipientEmail: 'sarah.smith@hss.org.uk',
    templateName: 'OTP Verification',
    subject: 'HSS UK Admin — Your one-time password (OTP)',
    sentAt: '2026-05-30T09:11:00Z',
    status: 'Delivered',
    triggeredBy: 'System — Admin Login (LOG-002)',
    contentPreview: 'Hello Sarah, your one-time password for HSS UK Admin Portal login is: 847291. This OTP is valid for 5 minutes. Do not share this with anyone...',
  },
  {
    id: 'EML-003',
    recipientName: 'Raj Sharma (Guardian)',
    recipientEmail: 'raj.sharma.guardian@gmail.com',
    templateName: 'Parental Consent Request',
    subject: 'Action Required — Parental consent needed for Deepak Sharma\'s HSS membership',
    sentAt: '2026-05-29T10:02:00Z',
    status: 'Delivered',
    triggeredBy: 'System — Member Registration (MBR-031)',
    contentPreview: 'Dear Raj Sharma, your child Deepak Sharma has applied for HSS UK membership. As Deepak is under 18, we require your consent to proceed. Please click the link below to review and approve...',
  },
  {
    id: 'EML-004',
    recipientName: 'Nisha Kapoor',
    recipientEmail: 'nisha.kapoor@gmail.com',
    templateName: 'Event Invitation',
    subject: 'You\'re invited — HSS Annual General Meeting 2026',
    sentAt: '2026-05-29T11:05:00Z',
    status: 'Delivered',
    triggeredBy: 'System — Event Created (EVT-006)',
    contentPreview: 'Dear Nisha, you are invited to attend the HSS Annual General Meeting 2026 at Harrow Activity Centre on 24 May 2026, 15:30–21:30. This is a free event. Please register your attendance...',
  },
  {
    id: 'EML-005',
    recipientName: 'Unknown Recipient',
    recipientEmail: 'invalid.email@@hss.org',
    templateName: 'Password Reset',
    subject: 'Reset your HSS UK Admin password',
    sentAt: '2026-05-29T14:32:00Z',
    status: 'Failed',
    triggeredBy: 'Self — Forgot Password (Admin Portal)',
    failureReason: 'Invalid email address format — rejected by mail server',
    contentPreview: 'Hello, a password reset was requested for your HSS UK Admin account. Click the link below to set a new password. This link expires in 30 minutes...',
  },
  {
    id: 'EML-006',
    recipientName: 'Vikram Singh',
    recipientEmail: 'vikram.singh@gmail.com',
    templateName: 'Welcome Email',
    subject: 'Welcome to Hindu Swayamsevak Sangh UK 🙏',
    sentAt: '2026-05-28T09:02:00Z',
    status: 'Delivered',
    triggeredBy: 'System — Member Registration (MBR-209)',
    contentPreview: 'Dear Vikram, welcome to HSS UK! We are delighted to have you as part of our community. Your member ID is MBR-209. You are registered at Manchester Central Activity Centre as Ghatnayak...',
  },
  {
    id: 'EML-007',
    recipientName: 'Manchester Central Members (15)',
    recipientEmail: 'group:manchester-central@hss.org.uk',
    templateName: 'Session Reminder',
    subject: 'Reminder — Manchester Shakha Sewa Shakha session tomorrow at 19:00',
    sentAt: '2026-05-27T10:00:00Z',
    status: 'Delivered',
    triggeredBy: 'System — Session Reminder (SES-014, 48h before)',
    contentPreview: 'Dear Members, this is a reminder that the Manchester Shakha — Sewa Shakha session is scheduled for tomorrow, 21 May 2026 at 19:00–21:00 at Manchester Central Activity Centre...',
  },
  {
    id: 'EML-008',
    recipientName: 'Anita Desai',
    recipientEmail: 'anita.desai.old@yahoo.co.uk',
    templateName: 'Attendance Confirmation',
    subject: 'Attendance recorded — Leeds Shakha, 23 May 2026',
    sentAt: '2026-05-26T11:08:00Z',
    status: 'Bounced',
    triggeredBy: 'System — Attendance Marked (ATT-1885)',
    failureReason: 'Mailbox does not exist — address may have been deactivated',
    contentPreview: 'Dear Anita, your attendance has been recorded for the Leeds Shakha — Fortnightly Milan session on 23 May 2026. Status: Present. Thank you for attending...',
  },
  {
    id: 'EML-009',
    recipientName: 'All Active Members (206)',
    recipientEmail: 'group:all-active@hss.org.uk',
    templateName: 'Announcement Notification',
    subject: 'HSS Announcement — Annual Camp 2026 registrations now open!',
    sentAt: '2026-05-25T11:35:00Z',
    status: 'Delivered',
    triggeredBy: 'System — Announcement Published (ANN-012)',
    contentPreview: 'Dear Members, we are excited to announce that registrations for HSS Annual Camp 2026 are now open! This is a wonderful opportunity for members of all age groups to participate in a week of Shakha activities, workshops and community service...',
  },
  {
    id: 'EML-010',
    recipientName: 'Sonia Shah',
    recipientEmail: 'sonia.shah@gmail.com',
    templateName: 'Member Status Updated',
    subject: 'Your HSS UK membership is now Active',
    sentAt: '2026-05-25T10:20:00Z',
    status: 'Delivered',
    triggeredBy: 'System — Status Change (MBR-045)',
    contentPreview: 'Dear Sonia, great news! Your HSS UK membership status has been updated to Active. Your parental consent has been received and verified. You can now access all member features...',
  },
  {
    id: 'EML-011',
    recipientName: 'Meera Iyer (Guardian notification)',
    recipientEmail: 'iyer.family@gmail.com',
    templateName: 'Guardian Consent Confirmation',
    subject: 'Parental consent confirmed — Meera Iyer\'s HSS membership',
    sentAt: '2026-05-24T10:05:00Z',
    status: 'Delivered',
    triggeredBy: 'System — Consent Granted (MBR-078)',
    contentPreview: 'Dear Guardian, thank you for providing parental consent for Meera Iyer\'s HSS UK membership. Meera\'s membership is now active. For any questions, please contact your local Activity Centre coordinator...',
  },
  {
    id: 'EML-012',
    recipientName: 'Suresh Pillai',
    recipientEmail: 'suresh.pillai@hotmail.com',
    templateName: 'Event Invitation',
    subject: 'You\'re invited — Cultural Evening, Edinburgh, 11 Jun 2026',
    sentAt: '2026-05-23T09:05:00Z',
    status: 'Delivered',
    triggeredBy: 'System — Event Published (EVT-005)',
    contentPreview: 'Dear Suresh, you are invited to the HSS Cultural Evening at Edinburgh Activity Centre on 11 June 2026, 18:00–21:00. Enjoy an evening of music, dance, and cultural performances. Admission is free...',
  },
  {
    id: 'EML-013',
    recipientName: 'John Doe',
    recipientEmail: 'john.doe@hss.org.uk',
    templateName: 'Password Reset',
    subject: 'Reset your HSS UK Admin password',
    sentAt: '2026-05-22T08:02:00Z',
    status: 'Delivered',
    triggeredBy: 'Self — Forgot Password (Admin Portal)',
    contentPreview: 'Hello John, a password reset was requested for your HSS UK Super Admin account. Click the link below to set a new password. This link expires in 30 minutes. If you did not request this, please contact IT support immediately...',
  },
  {
    id: 'EML-014',
    recipientName: 'Amit Rao',
    recipientEmail: 'amit.rao.hss@outlook.com',
    templateName: 'OTP Verification',
    subject: 'HSS UK — Your one-time password (OTP)',
    sentAt: '2026-05-21T09:02:00Z',
    status: 'Failed',
    triggeredBy: 'System — Admin Login (Admin Portal)',
    failureReason: 'Mailbox full — recipient inbox has exceeded its storage limit',
    contentPreview: 'Hello Amit, your one-time password for HSS UK Admin Portal login is: 319047. This OTP is valid for 5 minutes. Do not share this with anyone...',
  },
  {
    id: 'EML-015',
    recipientName: 'Leeds Shakha Members (14)',
    recipientEmail: 'group:leeds-north@hss.org.uk',
    templateName: 'Session Reminder',
    subject: 'Reminder — Leeds Shakha Fortnightly Milan session this Saturday at 14:00',
    sentAt: '2026-05-21T10:00:00Z',
    status: 'Delivered',
    triggeredBy: 'System — Session Reminder (SES-012, 48h before)',
    contentPreview: 'Dear Members, this is a reminder that the Leeds Shakha — Fortnightly Milan session is scheduled for Saturday, 23 May 2026 at 14:00–16:00 at Leeds North Activity Centre. Please ensure you arrive on time...',
  },
];
