export type RefundStatus = 'requested' | 'approved' | 'processed' | 'rejected';
export type RefundReason = 'event-cancelled' | 'duplicate-payment' | 'unable-to-attend' | 'payment-error' | 'other';

export interface RefundRecord {
  id: string;
  eventId: string;
  eventName: string;
  requesterName: string;
  requestedDate: string;
  processedDate?: string;
  amount: number;
  status: RefundStatus;
  reason: RefundReason;
  country: string;
  region: string;
  town: string;
  activityCentre: string;
}

export const mockRefunds: RefundRecord[] = [
  {
    id: 'REF-001',
    eventId: 'EVT-105',
    eventName: 'Fundraising Gala',
    requesterName: 'Arjun Sharma',
    requestedDate: '2026-05-23T09:20:00Z',
    processedDate: '2026-05-24T11:00:00Z',
    amount: 75,
    status: 'processed',
    reason: 'unable-to-attend',
    country: 'HSS Ireland',
    region: 'Dublin',
    town: 'Dublin City',
    activityCentre: 'Dublin Activity Centre',
  },
  {
    id: 'REF-002',
    eventId: 'EVT-105',
    eventName: 'Fundraising Gala',
    requesterName: 'Rahul Mehta',
    requestedDate: '2026-05-24T13:10:00Z',
    amount: 75,
    status: 'approved',
    reason: 'duplicate-payment',
    country: 'HSS Ireland',
    region: 'Dublin',
    town: 'Dublin City',
    activityCentre: 'Dublin Activity Centre',
  },
  {
    id: 'REF-003',
    eventId: 'EVT-108',
    eventName: 'Winter Carnival',
    requesterName: 'Kavita Nair',
    requestedDate: '2026-05-25T10:00:00Z',
    amount: 15,
    status: 'requested',
    reason: 'payment-error',
    country: 'HSS UK',
    region: 'Scotland',
    town: 'Glasgow',
    activityCentre: 'Glasgow Activity Centre',
  },
  {
    id: 'REF-004',
    eventId: 'EVT-110',
    eventName: 'Heritage Festival 2026',
    requesterName: 'Priya Patel',
    requestedDate: '2026-02-11T08:30:00Z',
    processedDate: '2026-02-12T09:45:00Z',
    amount: 30,
    status: 'processed',
    reason: 'event-cancelled',
    country: 'HSS United States',
    region: 'East Coast',
    town: 'New York',
    activityCentre: 'New York Activity Centre',
  },
  {
    id: 'REF-005',
    eventId: 'EVT-110',
    eventName: 'Heritage Festival 2026',
    requesterName: 'Arjun Sharma',
    requestedDate: '2026-02-13T15:10:00Z',
    amount: 30,
    status: 'rejected',
    reason: 'other',
    country: 'HSS United States',
    region: 'East Coast',
    town: 'New York',
    activityCentre: 'New York Activity Centre',
  },
  {
    id: 'REF-006',
    eventId: 'EVT-108',
    eventName: 'Winter Carnival',
    requesterName: 'Rohan Verma',
    requestedDate: '2026-05-27T18:30:00Z',
    amount: 15,
    status: 'requested',
    reason: 'unable-to-attend',
    country: 'HSS UK',
    region: 'Scotland',
    town: 'Glasgow',
    activityCentre: 'Glasgow Activity Centre',
  },
  {
    id: 'REF-007',
    eventId: 'EVT-105',
    eventName: 'Fundraising Gala',
    requesterName: 'Vikram Nair',
    requestedDate: '2026-05-25T16:40:00Z',
    processedDate: '2026-05-26T12:15:00Z',
    amount: 75,
    status: 'processed',
    reason: 'unable-to-attend',
    country: 'HSS Ireland',
    region: 'Dublin',
    town: 'Dublin City',
    activityCentre: 'Dublin Activity Centre',
  },
  {
    id: 'REF-008',
    eventId: 'EVT-102',
    eventName: 'Tech Workshop Series',
    requesterName: 'Arjun Sharma',
    requestedDate: '2026-05-28T09:05:00Z',
    amount: 25,
    status: 'approved',
    reason: 'duplicate-payment',
    country: 'HSS UK',
    region: 'Midlands',
    town: 'Birmingham',
    activityCentre: 'Birmingham East Activity Centre',
  },
  {
    id: 'REF-009',
    eventId: 'EVT-108',
    eventName: 'Winter Carnival',
    requesterName: 'Kavita Nair',
    requestedDate: '2026-05-29T10:25:00Z',
    amount: 15,
    status: 'requested',
    reason: 'unable-to-attend',
    country: 'HSS UK',
    region: 'Scotland',
    town: 'Glasgow',
    activityCentre: 'Glasgow Activity Centre',
  },
  {
    id: 'REF-010',
    eventId: 'EVT-110',
    eventName: 'Heritage Festival 2026',
    requesterName: 'Rahul Mehta',
    requestedDate: '2026-02-14T11:50:00Z',
    processedDate: '2026-02-15T10:00:00Z',
    amount: 30,
    status: 'processed',
    reason: 'payment-error',
    country: 'HSS United States',
    region: 'East Coast',
    town: 'New York',
    activityCentre: 'New York Activity Centre',
  },
];
